- src/test/java/EkaterinaLizinaTest.java
test Search For Language By Name
> [AT][Search][form]testSearchForLanguageBy_HappyPath() <EkaterinaLizina>

- src/test/java/IrynaOkunTest.java
[US] links
[TC] links
[AT] links
> [AT][Search][form] testSearchForLanguageByName_HappyPath() <IrynaOkun>

- src/test/java/NadiaPawlowaTest.java
[US] - https://trello.com/c/KEuJMCdF/25-usfunctionalsearchform-us-search-for-language-field
[TC] - https://trello.com/c/do4IE9Yz/60-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-nadiapawlowa
[AT] - https://trello.com/c/aP6eCgRu/102-atsearchform-testsearchforlanguagebynamehappypath-nadiapawlowa
> [AT][Search][form] testSearchForLanguageByName_HappyPath() <NadiaPawlowa>

- src/test/java/HenadzBuhlakouTest.java
[AT] - https://trello.com/c/spx9ZToj/128-atsearchform-testsearchforlanguagebynamehappypath-henadz-buhlakou
> [AT][Search][form]testSearchForLanguageByName_HappyPath() <Henadz Buhlakou>

- src/test/java/NstzyaTest.java
testSearchForLanguageByNameField_HappyPath() added
[US] - https://trello.com/c/pzVNdJn2/41-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/nL7ma0ki/72-tcsearchform-verify-if-user-searches-for-programming-language-by-name-he-can-see-the-list-of-realtive-results-nstzya
[AT] - https://trello.com/c/8olD8pKB/95-atsearchform-testsearchforlanguagebynamefieldhappypath-nstzya
> [AT][Search][form] testSearchForLanguageByNameField_HappyPath() Nstzya

- src/test/java/OlgaPriceTest.java
[US] https://trello.com/c/Pfi21TZq/49-usfunctionalsearchform-search-for-language-feild
[TC] https://trello.com/c/HZqieRgb/84-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-and-can-see-the-list-of-relative-results-olgaprice
[AT] https://trello.com/c/f4VkCpSJ/107-atsearchform-pr-name-olgaprice
> testSearchLanguageField_HappyPath added <OlgaPrice>

- src/test/java/Aidai001Test.java
[US] https://trello.com/c/fEnAowzE/54-usfunctionalpage-search-for-language-field-aidai
[TC] https://trello.com/c/6Dre4DV2/64-tc-test-name-aidai001
[AT] https://trello.com/c/78KexaDf/94-at-pr-name-aidai001
> testSearchForLanguageByName_HappyPath added <Aidai001>

- src/test/java/GalinaKuklevaTest.java
1. AT https://trello.com/c/YNFoazbq/122-atsearchform-testsearchforlanguagebynamehappypath-galina-kukleva
2. TC https://trello.com/c/cuURQ8UB/130-tcsearchform-verify-if-user-is-searching-for-a-programming-language-by-name-he-can-see-the-list-of-relative-results-galina-kukle
> testSearchForLanguageFeild_HappyPath() added

- src/test/java/IrynaDanilevskaTest.java
testSearchLanguageByName_HappyPath added
[US] - https://trello.com/c/GRtgfi9k/45-usfunctionalsearch-search-for-language-field 
[TC] - https://trello.com/c/aRjytWzM/77-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-svetakhudova  [AT] https://trello.com/c/pzc8J67U/106-atsearchform-testsearchlanguagebynamehappypath-svetakhudova
> [AT][Search][form] testSearchLanguageByName_HappyPath()<IrynaDanilevska>

- src/test/java/ElenaStratTest.java
Added test VerifyWishesFromTheTeamFirstParagraph_HappyPath() 
[US] https://trello.com/c/sngmyDYZ/137-usfunctionalstarttext-verify-wishes-from-the-team
[TC] https://trello.com/c/Z0qAZsrs/140-tcstarttext-verify-wishes-from-the-team-elenastrat
[AT] https://trello.com/c/1VzfpFzm/142-atstarttext-teststartforverifywishesfromtheteamhappypath-elenastrat
> ATStarttext_VerifyWishesFromTheTeam_ElenaStrat

- src/test/java/NikolayMarkov3Test.java
testSearchForLanguagesByName_HappyPath() added
[AT] - https://trello.com/c/6Dd00Yj8/150-atsearchform-testsearchforlanguagesbynamehappypath-nikolaymarkov3
> [AT][Search][form] testSearchForLanguagesByName_HappyPath() <NikolayMarkov3>

- src/test/java/MaxIasko99Test.java
[US] https://trello.com/c/myTMVzTE/154-usfunctionalsearchform-search-for-language-field
[TC] https://trello.com/c/K1QsOpQa/158-tcsearchform-verify-if-the-user-is-searching-for-a-programming-language-by-the-name-he-can-see-the-list-of-the-relative-results
[AT] https://trello.com/c/QwK3Iac1/159-atsearchform-testsearchforlanguagebynamehappypathmaxiasko
> [AT][Search][form] testSearchForLanguageByName_HappyPath()<MaxIasko>

- src/test/java/AnastasiaYYTest.java
[US] - https://trello.com/c/ylVq0ftJ/134-usstructuresearchform-search-for-language-field
[TC] - https://trello.com/c/CUDTmpm5/156-tcsearchform-verify-if-a-user-is-searching-for-programming-language-by-name-he-she-can-see-the-list-of-relative-results-anastasi
[AT] - https://trello.com/c/gsGaIC6U/165-atsearchform-testsearchforlanguagebynamehappypath-anastasiayy
> [AT][Search][form] testSearchForLanguageByName_HappyPath() <AnastasiaYY>

- src/test/java/YulyaNyuTest.java
testVerifyH2TagText_WhenClickingSubmenuTeam_HappyPath() added
[TC] - https://trello.com/c/h8oKHSwY/164-tcteammainheaderh2-verify-that-header-name-changed-when-user-click-submenu-team-yulyanyu
[AT] - https://trello.com/c/RUh2ZB2O/185-atteammainheaderh2-testverifh2tagtextwhenclickingsubmenuteamhappypath-yulyanyu
> [AT][Team][main][header][h2] testVerifyH2TagText_WhenClickingSubmenuTeam_HappyPath() <YulyaNyu>

- src/test/java/NstzyaTest.java
testHistoricInfoLink_WhenClickingOnLink_HappyPath() added
[TC] - https://trello.com/c/sr0jiilb/207-tcstartmainlink-verify-that-user-can-open-historic-information-link-in-text-on-main-nstzya
[AT] - https://trello.com/c/v2urccvJ/211-atstartmainlink-pr-name-nstzya
> [AT][Start][main][link] testHistoricInfoLink_WhenClickingOnLink_HappyPath() <Nstzya>

- src/test/java/MariaKuzhTest.java
[US] - https://trello.com/c/AVFCtac7/136-usfunctionalsearchform-search-for-language-field-mariakuzh 
[TC] - https://trello.com/c/lTXrWy1j/166-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-mariakuzh
[AT] - https://trello.com/c/zpe3duG0/167-atsearchform-testsearchforlanguagebynamehappypath-mariakuzh
> [AT][Search][form] testSearchForLanguageByName_HappyPath() <MariaKuzh>

- src/test/java/MariaStupenTest.java
[US] - https://trello.com/c/ElxsBzR1/138-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/jGtzzHUL/145-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-mariastupen
[AT] - https://trello.com/c/YGg0kd7r/146-atsearchform-pr-name-mariastupen
> [AT][Search][form] testSearchForLanguageByName_HappyPath() <mariastupen>

- src/test/java/KseniyaKudrinaTest.java
[US] - https://trello.com/c/CzH8Fn0i/178-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/xjFM05Db/177-tcstartform-verify-if-user-is-searching-for-programming-languahe-by-name-he-can-see-the-list-of-relative-results-kseniyakudrina
[AT] - https://trello.com/c/4rA88mIJ/179-atsearchform-testsearchforlanguagebyname-happypathkseniyakudrina
> [AT][Search][form]testSearchForLanguageByName_HappyPath() <KseniyaKudrina>

- src/test/java/VictoriaLemaTest.java
testIfTopListsReferenceOnTheFooterMenuRedirectsToTheTopListPage_WhenClickingOnIt() added
[US] -https://trello.com/c/AkkS2Fch/215-usmainfootertoplist-functionality-of-top-list-on-footervictorialema
[TC] - https://trello.com/c/qwuJ34rC/216-tcmainfootertoplist-verify-if-user-can-see-top-rated-languages-if-he-click-on-top-list-on-the-footer-victorialema
[AT] - https://trello.com/c/OLI8hPGb/217-atmainfootertoplist-testiftoplistsreferenceonthefootermenuredirectstothetoplistpagewhenclickingonit-victorialema
> [AT][Main][footer][toplist] testIfTopListsReferenceOnTheFooterMenuRedirectsToTheTopListPage_WhenClickingOnIt() <VictoriaLema>

- src/test/java/NadiyaPTest.java
[US]https://trello.com/c/scPhvzvX/200-usfunctionalsearchformsearch-for-language-field
[TC]https://trello.com/c/DRhIYSih/202-tcstartform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-nadiayp
[AT]https://trello.com/c/M7NV998G/203-atsearchformtestsearchforlanguagebynamehappypath-nadiyap
> [AT][Search][form] testSearchForLanguageByName_HappyPath()<NadiyaP>

- src/test/java/NataliiaOliverTest.java
created testTeamNames(), added method List<String> WebElementToString(List<WebElement> elementList)
[TC] - https://trello.com/c/qjNr9OEQ/232-tcstartnavigationsubmenuteam-verify-if-the-names-of-all-site-creators-are-displayed-nataliiaoliver
[AT] - https://trello.com/c/v8ZSYaaS/249-atstartnavigationsubmenuteam-testteamnames-nataliiaoliver
> [AT][Start][navigation][submenu][team] testTeamNames() <NataliiaOliver>

- src/test/java/NataliiaOliverTest.java
ATStartNavigationSubmenuTeam_testTeamLinks()_NataliiaOliver created, methods getTeamLinks() and getAllCreatorsLinks() created
[TC] - https://trello.com/c/mcApnkhY/274-tcstartnavigationsubmenuteam-verify-if-the-links-of-all-site-creators-are-displayed-nataliiaoliver
[AT] - https://trello.com/c/t2nC6jUU/279-atstartnavigationsubmenuteam-testteamlinks-nataliiaoliver
> [AT][Start][navigation][submenu][team] testTeamLinks() <NataliiaOliver>

- src/test/java/NstzyaTest.java
testSearchForLanguageByNameField_HappyPath() changed location of final variables
[RF] - https://trello.com/c/9iBQAJ5W/272-rfmainnavigationmenusearch-testsearchforlanguagebynamefieldhappypath-nstzya
> [RF][Main][navigation][menu][search] testSearchForLanguageByNameField_HappyPath() <Nstzya>

- src/test/java/AleksandrAkimovChgTest.java
testSearchForLanguageEmptyField_HappyPath() added
[US] - https://trello.com/c/ioQKXDOH/251-usfunctionalsearchform-search-for-language-empty-field-aleksandrakimovchg
[TC] - https://trello.com/c/CRsXQOy1/256-tcsearchform-verify-if-user-is-searching-for-programming-language-by-empty-field-he-can-see-the-list-of-0-resaults-aleksandrakim
[AT] - https://trello.com/c/2HZhGZW2/258-atsearchform-testsearchforlanguageemptyfieldhappypath-aleksandrakimovchg
> [AT][Search][form] testSearchForLanguageEmptyField_HappyPath() <AleksandrAkimovChg>

- src/test/java/NataliiaOliverTest.java
RF testTeamNames(), chenged loc from WebElements to private final constants
[RF] - https://trello.com/c/D3sdZHO3/280-rfstartnavigationsubmenuteam-testteamnames-nataliiaoliver
> [RF][Start][navigation][submenu][team] testTeamNames() <NataliiaOliver>

- src/test/java/TatyanaBelikovaTest.java
At search form search language field tatyana belikova
[US] - https://trello.com/c/f8JSGa4j/210-usfunctionalsearchform-search-for-language-field-tatyana-belikova
[TC] - https://trello.com/c/gA8SbQd0/264-tcsearchform-verify-if-user-is-searching-for-programming-languege-by-name-he-can-see-the-list-of-relative-resultstatyana-belikov
[AT] - https://trello.com/c/xx20gKt9/262-atsearchform-testsearchforlanguagefieldbynamehappypattatyana-belikova
> [AT] SearchForLanguageFieldByName_HappyPat<Tatyana-Belikova>

- src/test/java/IrynaDanilevskaTest.java
[US] - https://trello.com/c/ST9avavI/182-usfunctionalabcsubmenu-search-for-language-by-letter-or-number-name
[TC] - https://trello.com/c/HEg5XCAa/186-tcabcsubmenu-verify-that-languages-are-sorted-and-displayed-on-the-page-abc-by-selected-letter-of-submenuirynadanilevska
[AT] - https://trello.com/c/rHz6o5mM/189-atabcsubmenu-testsortinglanguagesbyletterafterselectingletterinsubmenuhappypathirynadanilevska
> [AT][ABC][submenu]TestSortinglanguagesByLetter_AfterSelectingLetterInSubmenuI<IrynaDanilevska>

- src/test/java/KseniyaKudrinaTest.java
testConfirmThatAddCommentOnPage_HappyPath() added
-without [US]
TC - https://trello.com/c/oFgRbzKd/230-tcmainnavigationmenuabc-confirm-the-add-commentkseniyakudrina
AT - https://trello.com/c/TRkvAFRx/231-atmainnavigationmenuabc-testconfirmthataddcommentonpagehappypath-kseniyakudrina
> [AT][Main][navigation][menu][abc] testConfirmThatAddCommentOnPage_HappyPath() <KseniyaKudrina>

- src/test/java/Katy1313Test.java
testBrowseLanguagesDefaultValue_HappyPath() added
[TC] - https://trello.com/c/3mOUSyMA/273-tcmainnavigationmenuabc-test-name-katy1313
[AT] - https://trello.com/c/C1mDgWkd/275-atmainnavigationmenuabc-pr-name-katy1313
> [AT][Main][navigation][menu][abc] testBrowseLanguagesDefaultValue_HappyPath() <katy1313>

- src/test/java/EnmedvTest.java
testVerifyTextInHeaderH2() added
[TC] - https://trello.com/c/raxkdy0T/263-tcimpressummain-headerverify-text-in-header-h2-enmedv
[AT] - https://trello.com/c/bP7Z04Ln/282-atimpressummain-header-testverifytextinheaderh2-enmedv
> [AT][Impressum][main][header] testVerifyTextInHeaderH2() <Enmedv>

- src/test/java/MariaKuzhTest.java
testVerifyTextTopListsToTheStartPage() added
[US] - https://trello.com/c/1BEo1nJI/222-usmainnavigationmenutoplist-verify-text-mariakuzh
[TC] - https://trello.com/c/OmohIAlT/223-tcmainnavigationmenutoplist-verify-if-user-can-see-correct-header-name-top-list-mariakuzh
[AT] - https://trello.com/c/xn4b8tcs/224-atmainnavigationmenutoplist-testverifytexttopliststothestartpage-mariakuzh
> [AT][Main][navigation][menu][toplist] testVerifyTextTopListsToTheStartPage() <MariaKuzh>

- src/test/java/SvetaKhudovaTest.java
testClickStartFromHomepage_HappyPath() added
[US] - https://trello.com/c/j0h9vx0j/190-usfunctionalmainnavigationmenustart-return-to-home-page
[TC] - https://trello.com/c/cfpSG8E0/240-tcfunctionalmainnavigationmenustart-verify-that-clicking-the-start-menu-from-home-page-will-refresh-the-page-svetakhudova
[AT] - https://trello.com/c/uhmdyZt4/245-atfunctionalmainnavigationmenustart-testclickstartfromhomepagehappypath
> [AT][Functional][Main][navigation][menu][start] testClickStartFromHomepage_HappyPath() <SvetaKhudova>

- src/test/java/LetanatolTest.java
[AT] - https://trello.com/c/h8dUDVFn/288-atsearchform-testsearchforlanguagebynamehappypath-letanatol
> [AT][Search][form] testSearchForLanguageByName_HappyPath() <Letanatol>

- src/test/java/NataliiaOliverTest.java
Modificators of locators and methods from class NataliiaOliverTest Changed
[RF] - https://trello.com/c/lTd83iwA/297-rf-classmodificatorschanged-nataliiaoliver
> [RF] ClassModificatorsChanged <NataliiaOliver>

- src/test/java/MaxIasko99Test.java
testVerifyingChoosingLanguage added
refactoring all
[US] - https://trello.com/c/e5EENTmN/236-usmainfooterabcfunctionalitybrowselanguage-verifyingchoosinglanguagemaxiasko
[TC] - https://trello.com/c/7EZqxpTW/242-tcmainfooterabcfunctionalitybrowselanguage-verifyingchoosinglanguagemaxiasko
[AT] - https://trello.com/c/3s9zrWcw/243-atmainfooterabcfunctionalitybrowselanguage-verifyingchoosinglanguagemaxiasko
> [AT][Main][Footer][abc][Functionality][BrowseLanguage] VerifyingChoosingLanguage<MaxIasko>

- src/test/java/IrynaDanilevskaTest.java
testDefaultStateOfABCPage_AfterNavigatingOnPage_HappyPath()
[US] - https://trello.com/c/ST9avavI/182-usfunctionalabcsubmenu-search-for-language-by-letter-or-number-name 
[AT] -https://trello.com/c/omaYLTbE/284-atabcsubmenu-testdefaultstateofabcpageafternavigatingonpagehappypathirynadanilevska
> [AT][ABC][Submenu]DefaultStateOfABCPage_AfterNavigatingOnPage<IrynaDanilevska>

- src/test/java/EkaterinaKochelorovaTest.java
testH2TagText_WhenChooseSubmenuLyrics added
[TC] - https://trello.com/c/eI0mN1pT/296-tclyricsmainheaderh2verify-displays-the-title-of-the-song-when-moving-from-the-start-menu-to-the-lyrics-submenuekaterinakochelor
[AT] - https://trello.com/c/pncjM1Rz/303-atlyricsmainheaderh2-testh2tagtextwhenchoosesubmenulyrics-ekaterinakochelorova
> [AT][Lyrics][main][header][h2] testH2TagText_WhenChooseSubmenuLyrics() <EkaterinaKochelorova>

- src/test/java/NstzyaTest.java
testHereLink_WhenClickingOnLink_HappyPath() added
[TC] - https://trello.com/c/jtcPe0Ax/307-tcstartmainlink-verify-that-user-can-open-here-link-in-text-on-main-nstzya
[AT] - https://trello.com/c/VUTpegoS/308-atstartmainlink-testherelinkwhenclickingonlinkhappypath-nstzya
> [AT][Start][main][link] testHereLink_WhenClickingOnLink_HappyPath() <Nstzya>

- src/test/java/AnzhelikaBaaTest.java
- src/test/java/runner/BaseTest.java
[TC][Start][Navigation][Submenu][Lyrics] - https://trello.com/c/mJRFOlY4/161-tcstartnavigationsubmenulyricsverify-if-the-user-searches-for-the-lyrics-of-the-song-99-bottles-of-beer-in-song-lyrics-submenu-h
[AT][Start][Navigation][Submenu][Lyrics] - https://trello.com/c/HmeKyGut/270-atstartnavigationsubmenulyricstestsonglyricssubmenuwhensearchingforlyricsofsong-anzhelikabaa
> [AT][Start][Navigation][Submenu][Lyrics]Verify the Song Lyrics button exists, clickable and it redirects a User to the new page_AnzhelikaBaa

- src/test/java/IgorUlianovTest.java
testBrowseLanguagesByCategoryName_HappyPath() added
[TC] - https://trello.com/c/ZqM0c8D2/292-tcabcnavigationsubmenux-verify-if-user-is-browsing-programming-languages-by-category-they-can-see-the-list-of-relative-results-i
[AT] - https://trello.com/c/Vl4infFM/294-at-pr-name-github-username
> [AT][ABC][navigation][submenu][x] testBrowseLanguagesByCategoryName_HappyPath() <igorulianov>

- src/test/java/ATAchytyTest99.java
testSearchLanguageByName_HappyPath() added
[US] https://trello.com/c/vcvZYZKS/219-ussearchfrom-testsearchforlanguagebynamehappypath-achytyd
[TC] https://trello.com/c/qGDANxYK/220-tcsearchfrom-testsearchforlanguagebynamehappypath-achytyd
[AT] https://trello.com/c/tOabpXa1/218-atsearchfrom-testsearchforlanguagebynamehappypath-achytyd
> [AT][Search][from] testSearchForLanguageByName_HappyPath() <AchytyD>

- src/test/java/MariyaSvetlovaTest.java
testVerifyHeaderH1OnStartPage added
[US] - https://trello.com/c/QtoPzLcq/285-usfunctionalmainheaderh1-verify-header-on-start-page
[TC] - https://trello.com/c/3kpnufqP/286-tcmainheaderh1-verify-header-on-start-pagemariyasvetlova
[AT] - https://trello.com/c/WYrEcDKA/305-atmainheaderh1-verify-header-on-start-page-mariyasvetlova
> [AT][Main][header][h1] Verify header on start page <MariyaSvetlova>

- src/test/java/IrinaDud_Test.java
testVerifyTextHeader1_HappyPath()  added
[US] - https://trello.com/c/Lxau2sZw/319-usfunctionalmainheader-h1verify-header1
[TC] - https://trello.com/c/WrNUdDRg/322-tcmainheaderverify-if-users-are-able-to-see-the-title-of-the-wedside-when-users-enter-on-the-main-pageirinadud
[AT] - https://trello.com/c/K1GCGQJj/323-atmainheader-testverifytextheader1happypath-irinadud
> [AT][Main][header]testVerifyTextHeader1_HappyPath()<IrinaDud>

- src/test/java/NstzyaTest.java
testSubmitYourOwnCodeLink_WhenClickingOnLink_HappyPath() added
[TC] - https://trello.com/c/ZsD8OyE4/311-tcstartmainlink-verify-that-user-can-open-submit-your-own-piece-of-code-link-in-text-on-main-nstzya
[AT] - https://trello.com/c/IhaGLgag/312-atstartmainlink-testsubmityourowncodelinkwhenclickingonlinkhappypath-nstzya
> [AT][Start][main][link] testSubmitYourOwnCodeLink_WhenClickingOnLink_HappyPath() <Nstzya>

- src/test/java/EnmedvTest.java
testVerifyTextInHeaderH3() added
TC - https://trello.com/c/Pe7TTgy4/324-tcimpressummainheader-verify-text-in-header-h3-enmedv
AT - https://trello.com/c/smeZMRtR/283-atimpressummainheader-testverifytextinheaderh3-enmedv
> [AT][Impressum][main][header] testVerifyTextInHeaderH3() <Enmedv>

- src/test/java/KseniyaKudrinaTest.java
**Comment** - testConfirmNewTitleOfPagePiet_HappyPath_KseniyaKudrina added
_without US_
**[TC]** - https://trello.com/c/PTV2QLMX/327-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-result
**[AT]** - https://trello.com/c/PEJYDG4H/328-atmainnavigationmenutoplist-testconfirmnewtitleofpagepiethappypath-kseniyakudrina
> [AT][Main][navigation][menu][toplist] testConfirmNewTitleOfPagePiet_HappyPath()KseniyaKudrina

- src/test/java/VeranikaCharlotteTest.java
testSearchLanguageField_HappyPath() added
[TC] - https://trello.com/c/bGWlKs9K/313-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-veranikacharlo
[AT] - https://trello.com/c/btP4Y5QR/314-atsearchform-testsearchlanguagefieldhappypath-veranikacharlotte
> [AT][Search][form] testSearchLanguageField_HappyPath() <VeranikaCharlotte>

- src/test/java/Yuliya14Test.java
test: click the Guestbook button to go to the guestbook page
> testMainNavigationButtonGuestbook_HappyPath() added

- src/test/java/SvetaSV15Test.java
testNavigatingTheSiteToFindTheNamesOfTeamMembers_HappyPath() added
[TC] - https://trello.com/c/Ta5qMZ9E/320-tcstartnavigationsubmenuteam-make-sure-that-if-the-user-searches-for-the-names-of-the-creators-of-the-site-he-will-also-get-a-st
[AT] - https://trello.com/c/DwkK5kiJ/321-atstartnavigationsubmenuteam-testnavigatingthesitetofindthenamesofteammembers-svetasv15
> testNavigatingTheSiteToFindTheNamesOfTeamMembers_HappyPath() added

- src/test/java/SvetaKhudovaTest.java
testClickStartFromSearchLanguagesMenu_HappyPath() added
[US] https://trello.com/c/j0h9vx0j/190-usfunctionalmainnavigationmenustart-return-to-home-page
[TC] https://trello.com/c/MfzsbGbf/241-tcfunctionalmainnavigationmenustart-verify-that-clicking-the-start-menu-from-search-languages-menu-will-redirected-user-to-the-h
[AT] https://trello.com/c/FJWSFnNW/244-atfunctionalmainnavigationmenustart-pr-name-svetakhudova
> testClickStartFromSearchLanguagesMenu_HappyPath() added

- src/test/java/NstzyaTest.java
testGuestbookLink_WhenClickingOnLink_HappyPath() added
[TC] - https://trello.com/c/yeKfwYhg/338-tcstartmainlink-verify-that-user-can-open-guestbook-link-in-text-on-main-nstzya
[AT] - https://trello.com/c/365f26RK/339-atstartmainlink-testguestbooklinkwhenclickingonlinkhappypath-nstzya
> [AT][Start][main][link] testGuestbookLink_WhenClickingOnLink_HappyPath() <Nstzya>

- src/test/java/IrynaDanilevskaTest.java
testSortingLanguagesByLetter_AfterSelectingLetterInSubmenu_HappyPath  was refactored:
[RF] - https://trello.com/c/yPkSKMRF/332-rfabcsubmenu-testsortinglanguagesbyletterafterselectingletterinsubmenuhappypathirynadanilevska
> [RF][ABC][submenu] testSortinglanguagesByLetter_AfterSelectingLetterInSubmenu_HappyPath<IrynaDanilevska>

- src/test/java/EnmedvTest.java
testVerifyTextOnThePageImpressum() added
TC - https://trello.com/c/UxbqGqRT/336-tcimpressummaintext-verify-text-on-the-page-impressum-enmedv
AT - https://trello.com/c/8dvg4rWF/337-atimpressummaintext-testverifytextonthepageimpressum-enmedv
> [AT][Impressum][main][text] testVerifyTextOnThePageImpressum() <Enmedv>

- src/test/java/AnastassiaITest.java
Anastassias branch testSearchForLanguage_HappyPath() added
[TC] - https://trello.com/c/9ZGXzEQr/331-tcsearchformverify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-resultsanastassiai
[AT] - https://trello.com/c/XCJROBhK/333-atsearchformtestsearchforlanguagehappypathanastassiai
>  [AT][Search][form]testSearchForLanguage_HappyPath()<AnastassiaI>

- src/test/java/MariaKuzhTest.java
testVerifyLinkTextWhenClickTopLists() added
[US] - https://trello.com/c/extbcCUt/281-usmainnavigationmenutoplist-verify-link-text-mariakuzh
[TC] - https://trello.com/c/3Z7KIizr/316-tcmainnavigationmenutoplist-verify-if-user-can-see-the-change-url-when-the-clicked-button-top-lists-mariakuzh
[AT] - https://trello.com/c/YepyQxBF/317-atmainnavigationmenutoplist-testverifylinktextwhenclicktoplists-mariakuzh
> [AT][Main][navigation][menu][toplist] testVerifyLinkTextWhenClickTopLists() <MariaKuzh>

- src/test/java/VerafesTest.java
StartNavigationSubmenuInfoVerifyInfoLabelText added
[TC] - https://trello.com/c/XALxsFwr/343-tcstartnavigationsubmenuinfo-verify-submenu-history-label-verafes
https://trello.com/c/apaPJ3Cc/345-atstartnavigationsubmenuinfo-testsubmenuinfolabeltexthappypath-verafes
[AT] - https://trello.com/c/apaPJ3Cc/345-atstartnavigationsubmenuinfo-testsubmenuinfolabeltexthappypath-verafes
> [AT][Start][navigation][submenu][info] Verify submenu History label text <verafes>

- src/test/java/NstzyaTest.java
testTeamMembersLink_WhenClickingOnLink_HappyPath() added
[TC] - https://trello.com/c/0bLH9Gal/346-tcstartmainlink-verify-that-user-can-open-team-members-link-in-text-on-main-nstzya
[AT] - https://trello.com/c/8RpkcyzY/347-atstartmainlink-testteammemberslinkwhenclickingonlinkhappypath-nstzya
> [AT][Start][main][link] testTeamMembersLink_WhenClickingOnLink_HappyPath() <Nstzya>

- src/test/java/EkaterinaKochelorovaTest.java
testPTagText_WhenChooseSubmenuLyrics added
[TC] - https://trello.com/c/xCr9U8Ak/359-tclyricsmaintext-verify-lyrics-displayed-when-moving-from-the-start-menu-to-the-lyrics-submenuekaterinakochelorova
[AT] - https://trello.com/c/zG9yC54N/358-atlyricsmaintext-testptagtextwhenchoosesubmenulyrics-ekaterinakochelorova
> [AT][Lyrics][main][text] testPTagText_WhenChooseSubmenuLyrics() <EkaterinaKochelorova>

- src/test/java/HenadzBuhlakouTest.java
testClickOnStartInFooter_HappyPath() added
[AT] - https://trello.com/c/bDrGFxKo/357-atmainfooterstart-testclickonstartinfooterhappypath-henadzbuhlakou
[TC] - https://trello.com/c/grsqw2TN/356-tcmainfooterstarttestclickonstartinfooterhappypathhenadzbuhlakou
> [AT][Main][footer][start] testClickOnStartInFooter_HappyPath() <HenadzBuhlakou>

- src/test/java/AndreiMironauTest.java
testH2TagTextHeaderMain_HappyPath()
[US] - https://trello.com/c/nD6reuK2/298-usfunctionalmainheader-verify-h2-tag-text
[TC] - https://trello.com/c/rA1FnlT4/302-tcmainheader-verify-text-subtitle-h2-on-main-page-andrei-mironau
[AT] - https://trello.com/c/agcyY7e1/304-atmainheader-testh2tagtextheadermainhappypath-andrei-mironau
> [AT][Main][Header] testH2TagTextHeaderMain_HappyPath() <AndreiMironau>

- src/test/java/Albina_starTest.java
[TC] - https://trello.com/c/YNgqhTB9/341-tcmainfootersearch-languages-verify-the-text-search-languages-albina-star
[AT] - https://trello.com/c/qLN96Juh/342-atmainfootersearch-languages-verify-the-text-search-languages-albina-star
> [AT][Main][footer][Search Languages] Verify the text Search Languages footer field_HappyPath() <Albina-star>

- src/test/java/AramH20Test.java
test_MainFooterGuestBookv2 added
SU - https://trello.com/c/DISMqxCn/366-usfunctionalmenuguestbookv2-aramh20
PC - https://trello.com/c/50i15js7/367-tcmenuguestbook-verify-if-user-click-on-guest-button-he-can-see-the-page-with-lists-of-guests-aramh20
AT - https://trello.com/c/tbajN5e7/369-atmenuguestbook-testmainfooterguestbookv2-aramh20
> [Menu][GUESTBOOK] test_MainFooterGuestBookv2() <AramH20>

- src/test/java/AnastasiaYYTest.java
testVerifyTextInHeaderH3() added
[TC] - https://trello.com/c/OBcLYHmO/371-tcteammainheaderh3-verify-text-in-header-h3-anastasiayy
[AT] - https://trello.com/c/Bxwgasbc/379-atteammainheaderh3-testverifytextinheaderh3anastasiayy
> [AT][Team][main][header][h3] testVerifyTextInHeaderH3()<AnastasiaYY>

- src/test/java/NataliiaOliverTest.java
testClickabilityLsLaNetLink_OliverSchade() created, get and click methods created
[TC] - https://trello.com/c/f2Ufde73/372-tcstartnavigationsubmenuteam-verify-that-the-link-to-the-personal-page-of-the-site-creator-oliver-schade-is-clickable-nataliiaol
[AT] - https://trello.com/c/3nhIzvqi/374-atstartnavigationsubmenuteam-testclickabilitylslanetlinkoliverschade-nataliiaoliver
> [AT][Start][navigation][submenu][team] testClickabilityLsLaNetLink_OliverSchade() <NataliiaOliver>

- src/test/java/VeranikaCharlotteTest.java
testGuestbookFooterLink_WhenClickingOnLink_HappyPath() added
[TC] https://trello.com/c/Pwf6rNkZ/360-tcmainfooterguestbookv2-verify-the-text-guestbookv2-with-information-using-the-footer-menu-veranikacharlotte
[AT] https://trello.com/c/HfEU5EDI/383-atstartfooterlink-testguestbooklinkwhenclickingonlinkhappypath-veranikacharlotte
> [AT][Start][footer][link] testGuestbookFooterLink_WhenClickingOnLink_HappyPath() <VeranikaCharlotte>

- src/test/java/VerafesTest.java
testSubmenuInfo_VerufylinkText_HappyPath() added
[TC] - https://trello.com/c/yLpnMYyj/375-tcstartnavigationsubmenuinfo-verify-submenu-history-link-text-verafes
[AT] - https://trello.com/c/44I4LyKa/378-atstartnavigationsubmenuinfo-verify-submenu-history-link-text-verafes
also Modifier "final" was removed for String expectedResult  in testSubmenuInfoLabelText_HappyPath()
[RF] - https://trello.com/c/WoM0JBmp/380-rfstartnavigationsubmenuinfo-testsubmenuinfoverifylabeltexthappypath-verafes
> [AT][[Start][navigation][submenu][info] Verify submenu History link text <verafes>

- src/test/java/AnaLaraTest.java
testNavigationToLyricsSubmenu_HappyPath added
[US]: https://trello.com/c/JgB9l592/23-usfunctionalstartnavigationsubmenulyrics-testnavigationtolyricssubmenuhappypath-ana-lara
[TC]: https://trello.com/c/iHRpSVxS/318-tcfunctionalstartnavigationsubmenulyrics-test-navigation-to-lyrics-submenu-ana-lara
[AT]: https://trello.com/c/ePQDHsau/348-atfunctionalstartnavigationsubmenulyrics-testnavigationtolyricssubmenuhappypathana-lara
> [AT][Functional][Start][navigation][submenu][lyrics] testNavigationToLyricsSubmenu_HappyPath <Ana-Lara>

- src/test/java/NataliiaOliverTest.java
Refactoring testTeamLinks(), code modified
[RF] - https://trello.com/c/tQrkJBg6/382-rfrfstartnavigationsubmenuteam-testteamlinks-nataliiaoliver
> [RF][Start][navigation][submenu][team] testTeamLinks() <NataliiaOliver>

- src/test/java/AnastasiaYYTest.java
testVerifyH2HeaderText_TopListsMainPage() added
[AT] - https://trello.com/c/iI38hFsg/385-attoplistmainh2-testverifyh2headertexttoplistsmainpage-anastasiayy
[TC] - https://trello.com/c/mUzvcj2G/384-tctoplistmainh2-verify-h2-header-text-anastasiayy
> [AT][Toplist][main][h2] testVerifyH2HeaderText_TopListsMainPage_AnastasiaYY

- src/test/java/IrinaDud_Test.java
testFooterBrowseLanguages_HappyPath() added
[US] - https://trello.com/c/u0djH8l7/350-usmainfooterabc-browse-languages
[TC] - https://trello.com/c/u7q9SyKp/351-tcmainfooter-verify-if-user-is-on-the-page-browse-languages-clicking-on-button-browse-languagesirinadud
[AT] - https://trello.com/c/u7q9SyKp/351-tcmainfooter-verify-if-user-is-on-the-page-browse-languages-clicking-on-button-browse-languagesirinadud
> [AT][main][footer][abc] testFooterBrowseLanguages_HappyPath()IrinaDud

- src/test/java/NikolayMarkov3Test.java
testSearchForLanguagesEmpty_HappyPath() added
[TC] = https://trello.com/c/3WvIUNuf/153-tcfunctionsearch-search-for-language-field-empty-nikolaymarkov3
[AT] = https://trello.com/c/0LQERybz/155-atfunctionsearch-search-for-language-field-empty-happy-path-nikolaymarkov3
> [AT][Function][Search] Search for Language Field Empty _ Happy Path <nikolaymarkov3>

- src/test/java/IrynaDanilevskaTest.java
TestSearchLanguageField_HappyPath() was refactored: 
[RF] - https://trello.com/c/e1KxacQF/355-rfsearchformtestsearchlanguagefieldhappypath-irynadanilevska
> [RF][Search][form]testSearchLanguageField_HappyPath <IrynaDanilevska>

- src/test/java/Yuliya14Test.java
testMainNavigationButtonSubmitNewLanguage_HappyPath() added
[TC] https://trello.com/c/8r2aje0c/252-tcmainnavigationmenusubmitnewlanguage-click-on-the-submit-new-language-button-yuliya-14
[AT] https://trello.com/c/5D2VOClv/254-atmainnavigationmenusubmitnewlanguage-testmain-navigationbuttonsubmitnewlanguagehappypath-yuliya-14
[RF] https://trello.com/c/wJZdzZWk/387-rfatmainnavigationmenusubmitnewlanguage-testmain-navigationbuttonsubmitnewlanguagehappypath-yuliya-14
> [AT][Main][navigation][menu][submitnewlanguage] testMainNavigationButtonSubmitNewLanguage_HappyPath() <Yuliya-14> added

- src/test/java/AleksandrAkimovChgTest.java
testH2TagText_WhenClickZOnSubmenuNavigationBarABCMenu() added
[US] - https://trello.com/c/a1LQle1s/386-usabcnavigationsubmenuz-categoryzpage-aleksandrakimovchg
[TC] - https://trello.com/c/hKKEjhrW/389-tcabcnavigationsubmenuz-verify-the-text-of-page-namealeksandrakimovchg
[AT] - https://trello.com/c/BP3z4RkN/390-atabcnavigationsubmenuz-testh2tagtextwhenclickzonsubmenunavigationbarabcmenualeksandrakimovchg
> [AT][ABC][navigation][submenu][z] testH2TagText_WhenClickZOnSubmenuNavigationBarABCMenu() <AleksandrAkimovChg>

- src/test/java/NikolayMarkov3Test.java
testSearchSearchForLanguagesByNameJava_HappyPath() added
[TC] = https://trello.com/c/hs44FZjn/391-tcmainnavigationmenusearch-search-for-languages-by-name-java-nikolaymarkov3
[AT] = https://trello.com/c/jT4Ofuw1/392-atmainnavigationmenusearch-search-for-languages-by-name-java-nikolaymarkov3
> [AT][Main][navigation][menu][search] Search For Languages By Name Java <nikolaymarkov3>

- src/test/java/AnastassiaITest.java
testH2TagText_WhenTestSubmenuInfo()_added
[TC] - https://trello.com/c/FqjImzja/362-tc-test-name-github-username
[AT] - https://trello.com/c/3GRp4Xcu/363-at-pr-name-github-username
> [AT][Info][Main][]Header][h2]testH2TagText_WhenTestSubmenuInfo()_AnastassiaI

- src/test/java/TatyanaBelikovaTest.java
StartNavigationSubmenuImpressumVerifyInfoLabelText
[US] - https://trello.com/c/ERDJV5Vl/364-usfunctionalstartnavigationsubmenuimpressum-test-navigation-to-impressum-submenu-tatyana-belikova
[TC] - https://trello.com/c/Sg3yJ46h/365-tcfunctionalstartnavigationsubmenuimpressumverify-text-submenu-privacy-label-tatyana-belikova
[AT] - https://trello.com/c/J2EgAS9a/376-atstartnavigationsubmenuimpressum-testsubmenuimpressumlabeltexthappypath-tatyana-belikova
> [AT][Start][navigation][submenu][impressum] Verify submenu Privacy label text<Tatyana-Belikova>

- src/test/java/mbatozTest.java
verifyWishesFromTheTeamTest added
[US]https://trello.com/c/sngmyDYZ/137-usfunctionalstarttext-verify-wishes-from-the-team
> [AT][Start][text] testStartForVerifyWishesFromTheTeam() <mbatoz>

- src/test/java/LessonsTest.java
[RF] - https://trello.com/c/iNRuv8P4/402-rf-pr-name-lessons
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <Lessons>

- src/test/java/GalinaKuklevaTest.java
testSearchForLanguageByName_HappyPath() <GALINA-KUKLEVA> variables and methods added
[RF] https://trello.com/c/hpgxpuNa/417-rfsearchform-testsearchforlanguagebynamehappypath-galina-kukleva
> [RF][Search][form]testSearchForLanguageByNameHappyPath()<GALINA-KUKLEVA

- src/test/java/YulyaNyuTest.java
[RF] - https://trello.com/c/w3hGU7Xf/406-rfsearchform-testsearchforlanguagebynamehappypath-yulyanyu
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <YulyaNyu>

- src/test/java/MariannaLissTest.java
[RF] - https://trello.com/c/455nnhPc/420-rfsearchform-testsearchforlanguagebynamehappypath-mariannaliss
> [RF][Search][form] testSearchforLanguageByName_HappyPath() <MariannaLiss>

- src/test/java/VictoriaLemaTest.java
testSearchForLanguageByName_HappyPath() refactored, locators and methods created
[RF] - https://trello.com/c/yUz9dBGv/398-rfsearchform-testsearchforlanguagebynamehappypath-victorialema
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <VictoriaLema>

- src/test/java/EkaterinaLizinaTest.java
[RF] - https://trello.com/c/mCtBte0a/404-rfsearchform-testsearchforlanguagebynamehappypath-ekaterinalizina
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <ekaterinalizina>

- src/test/java/ATAchytyTest99.java
[RF] - https://trello.com/c/nVWTzvjJ/415-rf-pr-name-achytyd
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <AchytyD>

- src/test/java/VerafesTest.java
testSearchForLanguageByName_HappyPath() was refactored,
Two tests were ignored for refactoring
[RF] - https://trello.com/c/BCcEGTDT/414-rfsearchform-testsearchforlanguagebynamehappypathverafes
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <verafes>

- src/test/java/NataliiaOliverTest.java
testClickabilityETasteOrgLink_GregorScheithauer() created, methods and loc for this test created
[TC] - https://trello.com/c/2Bw46Tu2/427-tcstartnavigationsubmenuteam-verify-that-the-link-to-the-personal-page-of-the-site-creator-gregor-scheithauer-is-clickable-natal
[AT] - https://trello.com/c/6VUWQmMu/429-atstartnavigationsubmenuteam-testclickabilityetasteorglinkgregorscheithauer-nataliiaoliver
> [AT][Start][navigation][submenu][team] testClickabilityETasteOrgLink_GregorScheithauer() <NataliiaOliver>

- src/test/java/NstzyaTest.java
testSearchForLanguageByNameField_HappyPath() refactored, with modified methods 
[RF] - https://trello.com/c/8kDlo7iQ/397-rfsearchform-testsearchforlanguagebynamefieldhappypath-nstzya
> [RF][Search][form] testSearchForLanguageByNameField_HappyPath() <Nstzya>

- src/test/java/NikolayMarkov3Test.java
[RF] - https://trello.com/c/btUPLS9p/409-rfsearchform-testsearchforlanguagesnamehappypath-nikolaymarkov3
> [RF][Search][form] testSearchForLanguagesName_HappyPath() <nikolaymarkov3>

- src/test/java/VerafesTest.java
testSubmenuInfo_VerifyLabelText_HappyPath() was refactored
[RF] - https://trello.com/c/tOtXL4CV/431-rfstartnavigationsubmenuinfo-testsubmenuverifyinfolabeltexthappypathverafes
> [RF][Start][navigation][submenu][info] testSubmenu_VerifyInfoLabelText_HappyPath() <verafes>

- src/test/java/VerafesTest.java
testSubmenuInfo_VerifyLinkText_HappyPath() was refactored
private String SUB_MENU_OPTION = "" was removed
[RF] -  https://trello.com/c/G4EJrxkV/433-rfstartnavigationsubmenuinfo-testsubmenuinfoverifylinktexthappypath-verafes
> [RF][Start][navigation][submenu][info] testSubmenuInfo_VerifyLinkText_HappyPath() <verafes>

- src/test/java/NikolayMarkov3Test.java
testSearchForLanguageByNameEmpty_HappyPath() refactored, locators and methods added
[RF] - https://trello.com/c/FfgMOpJu/432-rfsearchform-testsearchforlanguagesnameemptyhappypath-nikolaymarkov3
> [RF][Search][form] testSearchForLanguagesNameEmpty_HappyPath() <nikolaymarkov3>

- src/test/java/NataliiaOliverTest.java
testClickabilityStsSynfloodDe_StefanScheler() created, loc and methods for this test created
[TC] - https://trello.com/c/ypI22Ul1/428-tcstartnavigationsubmenuteam-verify-that-the-link-to-the-personal-page-of-the-site-creator-stefan-scheler-is-clickable-nataliiao
[AT] - https://trello.com/c/6ie9ta0y/430-atstartnavigationsubmenuteam-testclickabilitystssynflooddestefanscheler-nataliiaoliver
> [AT][Start][navigation][submenu][team] testClickabilityStsSynfloodDeStefanScheler() <NataliiaOliver>

- src/test/java/NadiaPawlowaTest.java
https://trello.com/c/WWSKrBiw/400-rfsearchform-testsearchforlanguagebynamehappypath-nadiapawlowa
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <NadiaPawlowa>

- src/test/java/NikolayMarkov3Test.java
testSearchForLanguageByNameJava_HappyPath() refactored, locators and methods added
[RF] - https://trello.com/c/cFISeccA/434-rfsearchform-testsearchforlanguagesnamejavahappypath-nikolaymarkov3
> [RF][Search][form] testSearchForLanguagesNameJava_HappyPath() <nikolaymarkov3>

- src/test/java/AleksandrAkimovChgTest.java
testSearchForLanguageEmptyField_HappyPath() refactored, with modified methods
[RF] - https://trello.com/c/tuK6SfcD/440-rfsearchform-testsearchforlanguageemptyfieldhappypath-aleksandrakimovchg
> [RF][Search][form] testSearchForLanguageEmptyField_HappyPath() <AleksandrAkimovChg>

- src/test/java/YulyaNyuTest.java
testVerifyH2TagText_WhenClickingSubmenuTeam_HappyPath() refactored, locators and methods added
[RF] - https://trello.com/c/PGUlGpuD/441-rfteammainheaderh2-testverifyh2tagtextwhenclickingsubmenuteamhappypath-yulyanyu
> [RF][Team][main][header][h2] testVerifyH2TagText_WhenClickingSubmenuTeam_HappyPath() <YulyaNyu>

- src/test/java/VerafesTest.java
testSubmenuInfo_VerifyNavigation() added
[TC] https://trello.com/c/49uyRjWf/436-tcstartnavigationsubmenuinfo-verify-submenu-history-navigation-verafes
[AT] https://trello.com/c/kJdyQoQN/437-atstartnavigationsubmenuinfo-testsubmenuinfoverifynavigationverafes
> [AT][Start][navigation][submenu][info] testSubmenuInfo_VerifyNavigation()<verafes>

- src/test/java/AleksandrAkimovChgTest.java
testH2TagText_WhenClickZOnSubmenuNavigationBarABCMenu() refactored, locators and methods added
[RF] - https://trello.com/c/xt3LeitM/443-rfabcnavigationsubmenuz-testh2tagtextwhenclickzonsubmenunavigationbarabcmenualeksandrakimovchg
> [RF][ABC][navigation][submenu][z] testH2TagText_WhenClickZOnSubmenuNavigationBarABCMenu()<AleksandrAkimovChg>

- src/test/java/EkaterinaLizinaTest.java
[AT] - https://trello.com/c/ClpDjRNX/425-atabcnavigationsubmenuc-testabcnavigationsubmenuclicklettercekaterinalizina
added test TestABCNavigationSubmenuClickLetterC
> [AT][ABC][navigation][submenu][c] testABCNavigationSubmenuClickLetterC<ekaterinalizina>

- src/test/java/VerafesTest.java
testClickOnLinkSubmenuInfo() refactored: 
-deleted custom getCurretURL() because it is a predefined java method
-changed the test name using the template: what where when
-refined code of the test 
-deleted unnecessary imports
[R] https://trello.com/c/WN3wMDZi/447-rfstartnavigationsubmenuinfo-testclickonlinksubmenuinfo-verafes
> [Start][navigation][submenu][info] testClickOnLinkSubmenuInfo() <verafes>

- src/test/java/NikolayMarkov3Test.java
RFSearchform_testSearchForLanguagesNameJava_HappyPath_nikolaymarkov3 added
[RF] - https://trello.com/c/E9Ohvrg6/444-rfsearchform-testsearchforlanguagesnameadjustingthevariablelocatorhappypath-nikolaymarkov3
> [RF][Search][form] testSearchForLanguagesName_AdjustingTheVariableLocator_HappyPath() <nikolaymarkov3>

- src/test/java/AnzhelikaBaaTest.java
RFSearchForm_testSearchForLanguageByName_HappyPath added
[RF][Search][Form]testSearchForLanguageByName_HappyPath<AnzhelikaBaa> - https://trello.com/c/ELEHqfKC/448-rfsearchformtestsearchforlanguagebynamehappypathanzhelikabaa
> [RF][Search][Form]testSearchForLanguageByName_HappyPath()_AnzhelikaBaa

- src/test/java/VictoriaLemaTest.java
testIfTopListsReferenceOnTheFooterMenuRedirectsToTheTopListPage_WhenClickingOnIt() refactored, locator and method added
[RF] -https://trello.com/c/NBJ3zVDk/445-rfmainfootertoplist-testiftoplistsreferenceonthefootermenuredirectstothetoplistpagewhenclickingonit-victorialema
> [RF][Main][footer][toplist] testIfTopListsReferenceOnTheFooterMenuRedirectsToTheTopListPage_WhenClickingOnIt() <VictoriaLema>

- src/test/java/AnzhelikaBaaTest.java
Rf start navigation submenu lyrics test song lyrics submenu when searching for lyrics of song happy path 
[RF][Start][navigation][submenu][lyrics] - https://trello.com/c/yQQkhgy8/449-rfstartnavigationsubmenulyricstestsonglyricssubmenuwhensearchingforlyricsofsonghappypath-anzhelikabaa
> [RF][Start][navigation][submenu][lyrics]testSongLyricsSubmenu_WhenSearchingForLyricsOfSong_HappyPath() AnzhelikaBaa

- src/test/java/MariaKuzhTest.java
[RF] - https://trello.com/c/zrREGsSk/453-rfsearchform-testsearchforlanguagebynamehappypath-mariakuzh
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <MariaKuzh>

- src/test/java/ElenaStratTest.java
testSearchforLanguageByName_HappyPath() refactored, locators and methods added
[RF] - https://trello.com/c/FkAHzBt0/407-rfsearchform-testsearchforlanguagebynamehappypath-elenastrat
> [RF][Search][form] testSearchforLanguageByName_HappyPath() <ElenaStrat>

- src/test/java/ElenaKudTest.java
[RF]https://trello.com/c/BlFzxT0P/454-rfsearchform-testsearchforlanguagebynamehappypath-elenakud
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <ElenaKud>

- src/test/java/AnzhelikaBaaTest.java
ATTeamMainImage_testImages_WhenChooseTeamSubmenu_HappyPath() added
[TC][Team][main][image] - https://trello.com/c/4C6gh9vX/334-tcteammainimageverify-if-a-user-clicks-on-team-submenu-he-can-see-two-static-images-anzhelikabaa
[AT][Team][main][image] - https://trello.com/c/SwTX9WS6/361-atteammainimage-pr-name-anzhelikabaa
> [AT][Team][main][image]testImages_WhenChooseTeamSubmenu_HappyPath()_AnzhelikaBaa

- src/test/java/Yuliya14Test.java
[RF] - https://trello.com/c/BId7kP5F/455-rfsearchform-testsearchforlanguagebyname-yuliya14
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <Yuliya14>

- src/test/java/mbatozTest.java
[RF] https://trello.com/c/Nq5Rujtq/416-rfsearchform-testsearchforlanguagebynamehappypath-mbatoz
> [RF][Search][form]testSearchforLanguageByName<mbatoz>

- src/test/java/VictoriaLemaTest.java
testIfToplistsFooterMenRedirectsToPageWithInformation_WhenClickingOnIt() refactored,a locator created, unrefactored test ignored
[RF]-https://trello.com/c/qKNuwesz/459-rfmainfootertoplist-testiftoplistsfootermenredirectstopagewithinformationwhenclickingonit-victorialema
> [RF][Main][footer][toplist] testIfToplistsFooterMenRedirectsToPageWithInformation_WhenClickingOnIt <VictoriaLema>

- src/test/java/AnastassiaITest.java
testSearchForLanguage_HappyPath() refactored, locators and methods added
[RF] - https://trello.com/c/h8WqbtCA/461-rf-pr-name-anastassia-i
> [RF][Search][form]testSearchForLanguage_HappyPath()<Anastassia-I>

- src/test/java/NadyaGlukharevaTest.java
testSearchForEmptySearch_HappyPath() added
[TC] - https://trello.com/c/fv4A4Z9H/438-tcsearchform-veryfy-sure-the-empty-lookup-doesnt-generate-a-table-of-results-nadya-glukhareva
[AT] - https://trello.com/c/3vgOtmHy/439-atsearchform-testsearchforemptysearchhappypath-nadya-glukhareva
> [AT][Search][form] testSearchForEmptySearch_HappyPath() <Nadya-Glukhareva>

- src/test/java/IrynaHryhorivTest.java
code from the lesson
[AT](https://trello.com/c/eAbQ2U84/467-atsearchform-testsearchforlanguagebynamehappypath-irynahryhoriv
> [AT][Search][form] testSearchForLanguageByName_HappyPath()_IrynaHryhoriv

- src/test/java/VictoriaLemaTest.java
testLanguageCategories_WhenSubmittingANewLanguage() refactored,locators and a method are created
[RF] - https://trello.com/c/m2pcFzjw/463-rfsubmitnewlanguagemaintext-testlanguagecategorieswhensubmittinganewlanguage-victorialema
> [RF][Submitnewlanguage][main][text] testLanguageCategories_WhenSubmittingANewLanguage() <VictoriaLema>

- src/test/java/Katy1313Test.java
testBrowseLanguagesDefaultValue_HappyPath() refactored, locators and methods added
[RF] - https://trello.com/c/ARjbasr3/471-rfsearchform-pr-name-katy1313
> [RF][Search][form] testSearchLanguageByName_HappyPath() <katy1313>

- src/test/java/IgorUlianovTest.java
[RF] - https://trello.com/c/fLPjAR8M/474-rfsearchform-testsearchforlanguagebynamehappypath-igorulianov
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <igorulianov>

- src/test/java/FrolovaqaTest.java
[RF] - https://trello.com/c/cL46v31K/487-rfsearchform-testsearchforlanguagebynamehappypath-frolovaqa
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <frolovaqa>

- src/test/java/NstzyaTest.java
testAllLinksInsideMain_WhenClickingOnLinks_HappyPath() added based on five ignored tests
[TC] - https://trello.com/c/O9AmqDP1/468-tc-test-name-github-username
[AT] - https://trello.com/c/vfNNRFwn/469-at-pr-name-github-username
> [AT][Start][main][link] testAllLinksInsideMain_WhenClickingOnLinks_HappyPath() <Nstzya>

- src/test/java/Kot612005Test.java
testSearchForLanguageByName_HappyPath refactored, locators and mathods added
[RF] - https://trello.com/c/L55sD6v0/470-rfsearchform-testsearchlanguagebynamehappypath-kot612005
> [RF][Search][form] testSearchLanguageByName_HappyPath() <kot612005>

- src/test/java/AramH20Test.java
testSearchForLanguageByName_HappyPath() refactored, locatore and methods added
[RF] - https://trello.com/c/ruT79KDV/486-rfsearchform-testsearchforlanguagebynamehappypath-aramh20
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <AramH20>

- src/test/java/ViktoriiaKarpusTest.java
[US] - https://trello.com/c/ClGWHfvc/482-usabcnavigationsubmenuv-verify-if-user-is-clicking-on-letter-v-can-go-on-v-page
[TC] - https://trello.com/c/iwTrPJLS/483-tcabcnavigationsubmenuv-verify-if-user-is-clicking-on-letter-v-he-can-go-on-page-with-letter-vviktoriiakarpus
[AT] - https://trello.com/c/6Ip9UlOB/485-atabcnavigationsubmenuvverify-if-user-is-clicking-on-letter-v-he-can-go-on-page-with-letter-vviktoriiakarpus
> [AT][[ABC][navigation][submenu][v]testNavigationSubmenuClickLetterV()<ViktoriiaKarpus>

- src/test/java/Albina_starTest.java
test Verify List of Elements of Main Top List Submenu_HappyPath() 
[TC] - https://trello.com/c/OG57ZlJz/373-tcmaintoplistsubmenu-verify-list-of-elements-of-main-top-list-submenuhappypath-albina-star
[AT] - https://trello.com/c/ST0gpFAx/377-atmaintoplistsubmenu-verify-list-of-elements-of-main-top-list-submenuhappypath-albina-star
> [AT][Main][TopList][submenu] Verify List of Elements of Main Top List Submenu_HappyPath() <Albina-star>

- src/test/java/NataliaKengilTest.java
[RF] - https://trello.com/c/fjKccGpu/479-rf-pr-name-nataliakengil
> [RF][Search][Form] testSearchForLanguageByName_HappyPath() <NataliaKengil>

- src/test/java/YulyaNyuTest.java
testVerifyPageURLAndPageTitle() added
[TC] - https://trello.com/c/GzozOJzi/480-tcguestbookv2navigationsubmenusignv2verify-page-url-and-page-titleyulyanyu
[AT] - https://trello.com/c/Sfy2ocbc/497-atguestbookv2navigationsubmenusignv2testverifypageurlandpagetitle-yulyanyu
> [AT][Guestbookv2][navigation][submenu][signv2]testVerifyPageUrlAndPageTitle() <YulyaNyu>

- src/test/java/NstzyaTest.java
testHistoricInfo_Here_SubmitYourCode_Guestbook_TeamMembersLinks_WhenClickingOnLinks_HappyPath_Nstzya() deletion of five old tests
five [RF] cards:
1. https://trello.com/c/elC1VbJK/492-rfstartmainlink-testhistoricinfolinkwhenclickingonlinkhappypath-nstzya
2. https://trello.com/c/tiat7vrB/493-rfstartmainlink-testherelinkwhenclickingonlinkhappypath-nstzya
3. https://trello.com/c/szLSlpcl/494-rfstartmainlink-testsubmityourowncodelinkwhenclickingonlinkhappypath-nstzya
4. https://trello.com/c/F1gvIwUc/495-rfstartmainlink-testguestbooklinkwhenclickingonlinkhappypath-nstzya
5. https://trello.com/c/FvyamRRr/496-rfstartmainlink-testteammemberslinkwhenclickingonlinkhappypath-nstzya
> [RF][Start][main][link] testHistoricInfo_Here_SubmitYourCode_Guestbook_TeamMembersLinks_WhenClickingOnLinks_HappyPath() <Nstzya>

- src/test/java/SafOlgaTest.java
AT - https://trello.com/c/dPIfsfhF/507-atmainstartfooter-testfootermenubarmainpagesafronovaolga
US - https://trello.com/c/mcgL9ZVG/508-usfunctionalpagemainstartfooter
> [AT][Main][Start][Footer] testFooterMenuBarMainPage()<SafronovaOlga>

- src/test/java/MariaYanuTest.java
https://trello.com/c/tK682Y5g/510-rfmainnavigationmenustart-testheaderonthestartpagehappypath-mariayanu
> [RF][Main][navigation][menu][start] testHeaderOnTheStartPage_HappyPath() <MariaYanu>

- src/test/java/AnastasiaYYTest.java
refactor testSearchForLanguageByName_HappyPath(), amend locators, add methods
[RF] - [RF][Search][form] testSearchForLanguageByName_HappyPath() <AnastasiaYY>](https://trello.com/c/FTzlWx4g/481-rfsearchform-testsearchforlanguagebynamehappypath-anastasiayy)
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <AnastasiaYY>

- src/test/java/AleksandrAkimovChgTest.java
testLetterZ_WhenFindAndClickZOnSubmenuNavigationBarABCMenu() refactoed, locators and mathods added
[RF] - https://trello.com/c/mpZKpbR3/460-rfabcnavigationsubmenuz-testletterzwhenfindandclickzonsubmenunavigationbarabcmenualeksandrakimovchg
> [RF][ABC][navigation][submenu][z] testLetterZ_WhenFindAndClickZOnSubmenuNavigationBarABCMenu()<AleksandrAkimovChg>

- src/test/java/Katy1313Test.java
testBrowseLanguagesDefaultValue_HappyPath() refactored, methods added
[RF] - https://trello.com/c/pw5bBCer/513-rf-pr-name-katy1313
> [RF][Main][navigation][menu][abc] testBrowseLanguagesDefaultValue_HappyPath() <katy1313>

- src/test/java/TatyanaBelikovaTest.java
Rf submenu impressum test submenu impressum label text privacy
RF - https://trello.com/c/s1GTPrkS/515-rf-pr-name-tatyana-belikova
> [RF][Submenu][Impressum] testSubmenuImpressumLabelText_Privacy<Tatyana-Belikova>

- src/test/java/LarisaMokTest.java
[RF] - testSearchForLanguageByName_HappyPath() refactored, locators and methods added
https://trello.com/c/t7Ylw04K/408-rfsearchform-testsearchforlanguagebynamehappypath-larisa-mok
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <Larisa Mok>

- src/test/java/EkaterinaLizinaTest.java
[RF] - https://trello.com/c/OqlvMzrT/491-rf-pr-name-github-username
> [RF][ABC][navigation][submenu][c] testABCNavigationSubmenuClickLetterC<ekaterinalizina>

- src/test/java/MariaKuzhTest.java
testVerifyLinkTextWhenClickTopLists() refactored, locators and methods added
[RF] - https://trello.com/c/JQGWY1Fq/500-rfmainnavigationmenutoplist-testverifylinktextwhenclicktoplists-mariakuzh
> [RF][Main][navigation][menu][toplist] testVerifyLinkTextWhenClickTopLists() <MariaKuzh>

- src/test/java/AnastasiaYYTest.java
refactor testVerifyH2HeaderText_TopListsMainPage(), add loactor
[RF] - https://trello.com/c/1gbFtP2V/502-rftoplistmainh2-testverifyh2headertexttoplistsmainpage-anastasiayy
> [RF][Toplist][main][h2] testVerifyH2HeaderText_TopListsMainPage() <AnastasiaYY>

- src/test/java/KseniyaKudrinaTest.java
**Comment:**
RFMainnavigationmenuabc_testConfirmThatAddCommentOnPage_HappyPath _Kseniyakudrina refactor,locators added, method added.
**[RF]** - https://trello.com/c/R2CtWSBJ/511-rfmainnavigationmenuabc-testconfirmthataddcommentonpagehappypathkseniyakudrina
> [RF][Main][navigation][menu][abc] testConfirmThatAddCommentOnPage_HappyPath()<Kseniyakudrina>

- src/test/java/HenadzBuhlakouTest.java
[RF] - https://trello.com/c/oJwX44tq/517-rfsearchform-testsearchforlanguagebynamehappypath-henadzbuhlakou
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <HenadzBuhlakou>

- src/test/java/EnmedvTest.java
RFSearchform_testSearchLanguageByName_HappyPath_Enmedv refactored, locators and methods added
[RF] - https://trello.com/c/hrFNnlse/509-rfsearchform-testsearchlanguagebynamehappypath-enmedv
> [RF][Search][form] testSearchLanguageByName_HappyPath() <Enmedv>

- src/test/java/Albina_starTest.java
refactoring of testVerifyTextOfFooterMenuSearchLanguages_HappyPath()
[RF] - https://trello.com/c/zcCt6HjH/523-rfmainfootersearch-languagestestverifytextoffootermenusearchlanguageshappypathalbina-star
> [RF][Main][Footer][Search Languages]testVerifyTextOfFooterMenuSearchLanguages_HappyPath()<Albina-star>

- src/test/java/SvetaKhudovaTest.java
testSearchLanguageByName_HappyPath() refactored, locators and methods added
[RF] https://trello.com/c/mwJvOU11/411-rfsearchform-testsearchlanguagebynamehappypath-svetakhudova
> [RF][Search][form] testSearchLanguageByName_HappyPath() <SvetaKhudova>

- src/test/java/EkaterinaLizinaTest.java
[AT] - https://trello.com/c/H4T59Ws0/519-at
> [AT][Main][navigation][menu][guestbookv2] testVerifyErrorMessageIfSubmitWithoutCode_ekaterinalizina

- src/test/java/EkaterinaKochelorovaTest.java
testH2TagText_WhenChooseSubmenuLyrics() refactored, locators and methods added
[RF] - https://trello.com/c/ub2t4rik/527-rflyricsmainheaderh2-testh2tagtextwhenchoosesubmenulyrics-ekaterinakochelorova
> [RF][Lyrics][main][header][h2] testH2TagText_WhenChooseSubmenuLyrics() <EkaterinaKochelorova>

- src/test/java/ElenaKudTest.java
testVerifyH2HeaderTest_SubmitNewLanguage_HappyPath() added
[TC] - https://trello.com/c/OhZkNcHO/525-tcsubmitnewlanguagemainheaderh2verify-if-a-user-click-on-submit-new-language-menu-he-can-see-submit-new-language-header-namehapp
[AT] - https://trello.com/c/DO6Gxr5R/526-atsubmitnewlanguagemainheaderh2-testverifyh2headertestsubmitnewlanguagehappypathelenakud
> [AT][Submitnewlanguage][main][header][h2]testVerifyH2HeaderTest_SubmitNewLanguage_HappyPath()<ElenaKud>

- src/test/java/LarisaMokTest.java
[TC] - https://trello.com/c/2P0mrZax/541-tc-test-name-larisamok
[AT] - https://trello.com/c/gzaSVAwr/539-atzeromainheaderh2-testverifytextheader2onzeropagehappypathlarisamok
> ATZeroMainHeaderH2_testVerifyTextHeader2OnZeroPageHappyPath_LarisaMok

- src/test/java/EvgenyZagrebelnikovTest.java
testSearchForLanguageByName_HappyPath() refactored, locators and method added
[RF] - https://trello.com/c/uQrqkddS/533-rfsearchform-testsearchforlanguagebynamehappypath-evgenyzagrebelnikov
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <EvgenyZagrebelnikov>

- src/test/java/AndreiMironauTest.java
testH2TagTextHeaderMain_HappyPath() refactored, locators and methods added
[RF] - https://trello.com/c/PZyBhXtl/528-rfmainheader-testh2tagtextheadermainhappypath-andrei-mironau
> [RF][Main][Header] testH2TagTextHeaderMain_HappyPath() <Andrei Mironau>

- src/test/java/HenadzBuhlakouTest.java
testTextHeader2OnToplistReal_HappyPath() added
[TC] - https://trello.com/c/DnNEL3FZ/544-tctoplistsubmenutoplistrealh2-testtextheader2ontoplistrealhappypathhenadzbuhlakou
[AT] - https://trello.com/c/udc1AvGk/545-attoplistsubmenutoplistrealh2-testtextheader2ontoplistrealhappypathhenadzbuhlakou
Corrected PR name
> [AT][Toplist][Submenu][ToplistReal][H2]_testTextHeader2OnToplistReal_HappyPath_<HenadzBuhlakou>

- src/test/java/Albina_starTest.java
added testVerifyQuantityOfMainSubmitNewLanguagePleaseNoteList_HappyPath()
[TC] - https://trello.com/c/qSSiqyAy/536-tcmainsubmitnewlanguagepleasenotetestverifyquantityofmainsubmitnewlanguagepleasenotelisthappypathalbina-star
[AT] - https://trello.com/c/rKwYtlKp/535-atmainsubmitnewlanguagepleasenotetestverifyquantityofmainsubmitnewlanguagepleasenotelisthappypathalbina-star
> [AT][Main][SubmitNewLanguage][PleaseNote]testVerifyQuantityOfMainSubmitNewLanguagePleaseNoteList_HappyPath()<Albina-star>

- src/test/java/EkaterinaLizinaTest.java
[AT] - https://trello.com/c/YNiN0sWe/540-atmainnavigationmenutoplist-testverifythe1sttopratedreallanguageisdifferfromtopesotericlanguage-ekaterinalizina
[TC] - https://trello.com/c/csXRwMCx/537-tcmainnavigationmenutoplist-verify-that-1st-listed-language-has-highest-rating-ekaterinalizina
> [AT][Main][navigation][menu][toplist] testVerifyThe1stTopRatedRealLanguageIsDifferFromTopEsotericLanguage <ekaterinalizina>

- src/test/java/ElenaStratTest.java
testVerifyTextHeader1_HappyPath() added
[US] https://trello.com/c/zINvsD8z/555-usfunctionalheaderh1-verify-the-header-on-the-start-page
[TC] https://trello.com/c/wMgBdm0V/556-tcmainheaderh1-verify-the-header-on-the-start-page-elenastrat
[AT] https://trello.com/c/TbgwFJ6s/557-atmainheaderh1-verify-the-header-on-the-start-page-elenastrat
> [AT][Main][header][h1] testForVerifyTheHeaderOnTheStartPage_HappyPath <ElenaStrat>

- src/test/java/AnastasiaYYTest.java
add testAllLanguagesOnYPageContainsLetterY(), add locators
[TC] - https://trello.com/c/zYLaFWu5/542-tcabcnavigationsubmenuy-verifyifelementsstartwithyaredisplayedwhenclickingony-anastasiayy
[AT] - https://trello.com/c/p7xWmzDp/543-atabcnavigationsubmenuy-verifyifelementsstartwithyaredisplayedwhenclickingony-anastasiayy
> [AT][ABC][navigation][submenu][y] testAllLanguagesOnYPageContainsLetterY() <AnastasiaYY>

- src/test/java/IrynaDanilevskaTest.java
testDefaultStateOfABCPage_AfterNavigatingOnPage_HappyPath was refactored: 
[RF] - https://trello.com/c/yyUN1QSe/529-rfabcsubmenu-testdefaultstateofabcpageafternavigatingonpagehappypathirynadanilevska
> [RF][ABC][submenu] testDefaultStateOfABCPage_AfterNavigatingOnPage_HappyPath<IrynaDanilevska>

- src/test/java/Albina_starTest.java
- src/test/java/AnastasiaYYTest.java
- src/test/java/EkaterinaLizinaTest.java
- src/test/java/LarisaMokTest.java
- src/test/java/NstzyaTest.java
- src/test/java/TatyanaBelikovaTest.java
Reverts RedRoverSchool/AutomationQA_05#200
> Revert [RF][Search][form] <Tatayna-Belikova>

- src/test/java/EkaterinaKochelorovaTest.java
testPTagText_WhenChooseSubmenuLyrics() refactored, locators and methods added
[RF] - https://trello.com/c/yJNh01gk/562-rflyricsmaintext-testptagtextwhenchoosesubmenulyrics-ekaterinakochelorova
> [RF][Lyrics][main][text] testPTagText_WhenChooseSubmenuLyrics() <EkaterinaKochelorova>

- src/test/java/HenadzBuhlakouTest.java
testTextHeader2OnToplistEsoteric_HappyPath()added
[TC] - https://trello.com/c/1gXWCiwb/563-tctoplistsubmenutoplistesoteric-h2testtextheader2ontoplistesoterichappypathhenadzbuhlakou
[AT] - https://trello.com/c/0M8b4CFN/568-attoplistsubmenutoplistesoteric-h2testtextheader2ontoplistesoterichappypathhenadzbuhlakou
> [AT][Toplist][submenu][toplist_esoteric][h2]testTextHeader2OnToplistEsoteric_HappyPath<HenadzBuhlakou>

- src/test/java/Yuliya14Test.java
RF_testNavigationButtonsGuestbook_and_SubmitNewLanguage refactored
[RF] - https://trello.com/c/b7QGuDT8/456-rfmainnavigationmenuguestbookv2-testmainnavigationbuttonguestbookhappypath-yuliya14
[RF] - https://trello.com/c/uwTPo0o5/457-rfmainnavigationmenusubmitnewlanguage-testmainnavigationbuttonsubmitnewlanguagehappypathyuliya14
> [RF][Main][navigation][menu][guestbookv2][submitnewlanguage] testNavigationButtonsGuestbook_SubmitNewLanguage_HappyPath() <Yuliya14>

- src/test/java/MariaYanuTest.java
testNavigationMenuLinksAmountAndText() added
TC: https://trello.com/c/by7WO7UE/512-tcmainnavigationmenu-navigation-menu-contains-6-links-and-they-names-are-start-browse-languages-search-languages-top-lists-guest
AT: https://trello.com/c/78E2A0cS/566-atmainnavigationmenu-testnavigationmenulinksamountandtext-mariayanu
> [AT][Main][navigation][menu] testNavigationMenuLinksAmountAndText () <MariaYanu>

- src/test/java/AndriiKudlaTest.java
testSearchForLanguageByName_HappyPath()
[US] - https://trello.com/c/yBRVn1sp/504-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/iUwF4Zgw/505-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-andriikudla
[AT] - https://trello.com/c/NJLESCEk/506-atsearchform-testsearchforlanguagebynamehappypathandriikudla
> [AT][Search][form] testSearchForLanguageByName_HappyPath() <AndriiKudla>

- src/test/java/HenadzBuhlakouTest.java
testVerifyLinkTextAfterClickOnFooterMenuStart_HappyPath refactored, changed the name of the locator and the test name.
[RF] - https://trello.com/c/2da8gg5D/569-rfmainfooterstarttestverifylinktextafterclickonfootermenustarthappypath-henadzbuhlakou
> [RF][Main][footer][start]testVerifyLinkTextAfterClickOnFooterMenuStart_HappyPath() <HenadzBuhlakou>

- src/test/java/AramH20Test.java
test_ABCVerifyByLetterCategoryInformation() edded
[US] - [AT][Functional][ABC]VerifyIfUserIsSearchingForByLetterAndCanSeeTheLisOFCategoryInformation <AramH20>
[TC] - https://trello.com/c/ouM0raOa/549-tcfunctionalabctest-category-pages-aramh20
[AT} -https://trello.com/c/8Ilx3tQT/550-atfunctionalabcverifyifuserissearchingforbyletterandcanseethelisofcategoryinformation-aramh20
> [AT][Functional][ABC]VerifyIfUserIsSearchingForByLetterAndCanSeeTheLisOFCategoryInformation <AramH20>

- src/test/java/AnzhelikaBaaTest.java
testVerifyIfNamesOfLanguagesStartWithZ_WhenChoosingZSubmenu_HappyPath() added
[TC][Z][main][table][tr] - https://trello.com/c/dZvOuf4f/488-tczmaintabletr-verify-if-a-user-chooses-z-submenu-he-can-see-all-programming-languages-starting-with-letter-zanzhelikabaa
[AT][Z][main][table][tr] - https://trello.com/c/8gtO06HO/489-atzmaintabletrtestverifyifnamesoflanguagesstartwithzwhenchoosingzsubmenuhappypath-anzhelikabaa
> [AT][Z][main][table][tr]testVerifyIfNamesOfLanguagesStartWithZ_WhenChoosingZSubmenu_HappyPath() <AnzhelikaBaa>

- src/test/java/SvetaKhudovaTest.java
testClickStartFromHomepage_HappyPath refactored, locators and metods added
[RF] - https://trello.com/c/kOb05h00/567-rffunctionalmainnavigationmenustart-testclickstartfromhomepagehappypath-svetakhudova
> [RF][Functional][Main][navigation][menu][start] testClickStartFromHomepage_HappyPath() <SvetaKhudova>

- src/test/java/IrinaDud_Test.java
…testSearchForLanguageByName_HappyPath() refactored,locators and methods added
[RF] - https://trello.com/c/xMqgANgz/516-rfsearchform-testsearchforlanguagebynamehappypathirinadud
> [RF][Search][form] testSearchForLanguageByName_HappyPath()<IrinaDud>

- src/test/java/HenadzBuhlakouTest.java
testTextHeader2OnToplistAssembly_HappyPath() added
[TC] - https://trello.com/c/r8JixsQj/571-tctoplistsubmenutoplistassembly-h2testtextheader2ontoplistassemblyhappypath-henadzbuhlakou
[AT] - https://trello.com/c/ue0crBvz/574-attoplistsubmenutoplistassembly-h2testtextheader2ontoplistassemblyhappypath-henadzbuhlakou
> [AT][Toplist][submenu][toplist_assembly][h2]testTextHeader2OnToplistAssembly_HappyPath() <HenadzBuhlakou>

- src/test/java/AnastasiaYYTest.java
- src/test/java/AndreiMironauTest.java
add testNumberOfLanguagesOnPageY(), corrected name testAllLanguagesOnYPageStartWithLetterY() 
[TC] - https://trello.com/c/LscJJZFx/546-tcymaintabletr-verifynumberoflanguagesstartwithy-anastasiayy
[AT] - https://trello.com/c/Ocz4nKZc/547-atymaintabletr-testverifynumberoflanguagesstartswithy-anastasiayy
> [AT][Y][main][table][tr] testVerifyNumberOfLanguagesStartsWithY() <AnastasiaYY>

- src/test/java/IrynaDanilevskaTest.java
testContainsClickableAlphabetLettersAndRangeOfNumbers_HappyPath() was added:
[TC] - https://trello.com/c/HOXYcChY/570-tcabcsubmenu-verify-that-submenu-contains-and-clickable-alphabet-letters-and-range-of-numbersirynadanilevska 
[AT] - https://trello.com/c/Fkf4cfDq/573-atabcsubmenu-testsubmenucontainsclickablealphabetlettersandrangeofnumbers-irynadanilevska
> [AT][ABC][submenu] testSubmenuContainsClickableAlphabetLettersAndRangeOfNumbers <IrynaDanilevska>

- src/test/java/ViktoryiaKudrautsavaTest.java
testSearchForLanguageByName_HappyPath() refactered, locators and methods added
https://trello.com/c/hLrth0ZW/558-rf-pr-name-viktoryiakudrautsava
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <ViktoryiaKudrautsava>

- src/test/java/VeranikaCharlotteTest.java
Rf searchform test search for language by name happy path veranika charlotte
[RF] - https://trello.com/c/BeYXYVmE/499-rfsearchform-testsearchforlanguagebynamehappypath-veranikacharlotte
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <VeranikaCharlotte>

- src/test/java/TatyanaBelikovaTest.java
testSearchForLanguageFieldByName_HappyPath() refactored and methods added 
[RF] - trello.com/c/eTnQ6bbh/498-rfsearchform-testsearchforlanguagefieldbynamehappypathtatayna-belikova
> [RF][Search][form] <Tatayna-Belikova>

- src/test/java/SvetaKhudovaTest.java
testClickStartFromSearchLanguagesMenu refactored, locators and methods added
[RF] - https://trello.com/c/zZeFO1FL/576-rffunctionalmainnavigationmenustart-testclickstartfromsearchlanguagesmenuhappypathsvetakhudova
> [RF][Functional][Main][navigation][menu][start] testClickStartFromSearchLanguagesMenu_HappyPath<SvetaKhudova>

- src/test/java/MariyaSvetlovaTest.java
testVerifyHeaderH1OnStartPage and HeaderH2 refactored
[RF] - https://trello.com/c/q3N8mjSa/578-rfmainheaderh1h2-verify-header-on-start-page-mariyasvetlova
> [RF][Main][header][h1][h2] Verify header on start page <MariyaSvetlova>

- src/test/java/EnmedvTest.java
testVerifyTextInHeaderH2() refactored, locators and methods added
[RF] - https://trello.com/c/MKr1tKca/534-rfimpressummainheader-testverifytextinheaderh2-enmedv
> [RF][Impressum][main][header] testVerifyTextInHeaderH2() <Enmedv>

- src/test/java/AnzhelikaBaaTest.java
testH2PresenceAndColor_WhenChoosingTopRatedRealSubmenu_AnzhelikaBaa added
[TC][TopRatedReal][main][header][h2] - https://trello.com/c/ConJhRI2/579-tctopratedrealmainheaderh2-verify-if-a-user-can-see-the-header-of-the-page-and-the-color-hex-code-of-the-header-is-1b651canzheli
[AT][TopRatedReal][main][header][h2] - https://trello.com/c/sGaFoZQl/580-attopratedrealmainheaderh2-pr-name-anzhelikabaa
> [AT][TopRatedReal][main][header][h2]testH2PresenceAndColor_WhenChoosingTopRatedRealSubmenu_HappyPath()<AnzhelikaBaa>

- src/test/java/VerafesTest.java
testDeepLinkIsPresent_LanguageJavascript1948MainTable() added
[TC] - https://trello.com/c/Rdl2epzJ/584-tclanguagejavascript1948maintablelink-verify-deep-link-http-enwikipediaorg-wiki-javascript-is-present-verafes
[AT] - https://trello.com/c/lBtEjUZO/588-atlanguagejavascript1948maintablelink-testdeeplinkispresentlanguagejavascript1948maintable-verafes
> [AT][LanguageJavascript1948][main][table][link] testDeepLinkIsPresent_LanguageJavascript1948MainTable()<verafes>

- src/test/java/EkaterinaLizinaTest.java
AT-https://trello.com/c/gEA0qMIT/585-atatmainnavigationmenuguestbookv2testsignguestbookverifytextinalerturl-ekaterinalizina
TC - https://trello.com/c/kT1Pr1p3/583-tcmainnavigationmenuguestbookv2-verify-text-in-alert-ekaterinalizina
> [AT][Main][navigation][menu][guestbookv2]testSignGuestBookVerifyTextInAlertUrlAndAcceptAlert() <ekaterinalizina>

- src/test/java/LetanatolTest.java
testSearchForLanguageByName_HappyPath() refactored, locators and mothods added
[RF] - https://trello.com/c/r8ua6OJf/581-rfsearchform-testsearchforlanguagebynamehappypath-letanatol
> [RF][Search][form] testSearchForLanguageByName_HappyPath() <letanatol>

- src/test/java/Aidai001Test.java
[RF] https://trello.com/c/vodSCZmf/530-rfsearchform-testsearchforlanguagebynamehappypathaidai001
> [RF][Search][form] testSearchForLanguageByName_HappyPath()<Aidai001>

- src/test/java/Katy1313Test.java
testBrowseLanguagesLanguageSelectionH2HeaderTitle_HappyPath() refactored, methods and variables added
[RF] - https://trello.com/c/6kPfAr9A/591-rf-pr-name-katy1313
> [RF][Main][navigation][menu][abc] testBrowseLanguagesLanguageSelectionH2HeaderTitle_HappyPath()<katy1313>

- src/test/java/Albina_starTest.java
added testErrorMessageSubmitLanguageButton_HappyPath()
[TC]- https://trello.com/c/v4BdCJI9/597-tcmainsubmitnewlanguage-testerrormessagesubmitlanguagebuttonhappypath-albina-star
[AT]- https://trello.com/c/p0bzL4OK/598-atmainsubmitnewlanguage-testerrormessagesubmitlanguagebuttonhappypath-albina-star
> [AT][Main][SubmitNewLanguage] testErrorMessageSubmitLanguageButton_HappyPath() <Albina-star>

- src/test/java/AleksandrAkimovChgTest.java
testPagerNewComments_WhenClickNewCommentsOnSubmenuNavigationBarTopLitMenu() added, new locators added
[US] - https://trello.com/c/AoXHs9uW/575-usfunctionalnewcommentspageh2-verify-opening-a-page-with-new-comments-aleksandrakimovchg
[TC] - https://trello.com/c/FOuVHKof/599-tcnewcommentsmainform-verify-opening-a-page-with-new-comments-aleksandrakimovchg
[AT] - https://trello.com/c/54WpkM1g/601-atnewcommentsmainform-testpagernewcommentswhenclicknewcommentsonsubmenunavigationbartoplistmenu-aleksandrakimovchg
> [AT][NewComments][main][form] testPagerNewComments_WhenClickNewCommentsOnSubmenuNavigationBarTopListMenu() <ALeksandrAkimovChg>

- src/test/java/base/BaseTest.java
- src/test/java/old_tests/NataliiaOliverTest.java
- src/test/java/pages/BasePage.java
- src/test/java/pages/MainPage.java
- src/test/java/pages/SearchLanguagesPage.java
- src/test/java/pages/SearchLanguagesSubmenuPage.java
- src/test/java/pages/StartPage.java
- src/test/java/pages/StartSubmenuPage.java
- src/test/java/pages/TablePage.java
- src/test/java/tests/SearchLanguagesTest.java
Examples for 3 Page Object models
> POM1, POM2, POM3 models

- src/test/java/old_tests/AleksandrAkimovChgTest.java
- src/test/java/pages/BasePage.java
- src/test/java/pages/MainPage.java
- src/test/java/pages/NewCommentsPage.java
- src/test/java/pages/TopListsPage.java
- src/test/java/pages/TopListsSubmenuPage.java
- src/test/java/tests/NewCommentsTest.java
testPageNewCommentsH2() refactored to POM model
[RF] - https://trello.com/c/cDQBbfkm/610-rfnewcommentsmainheaderh2-testpagenewcommentsh2-aleksandrakimovchg
> [RF][NewComments][main][header][h2] testPageNewCommentsH2() <ALeksandrAkimovChg>

- src/test/java/old_tests/GoryankaTest.java
[US]https://trello.com/c/2jkMVSDV/590-usfunctionalsearchform-search-for-language-field
[TC]https://trello.com/c/yArcTqPP/595-tcsearchform-verify-if-the-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-goryanka
[AT]https://trello.com/c/dLCmK3fC/606-atsearchform-pr-name-goryanka
> [AT][Search][form] testSearchForLanguageByName_HappyPath() <Goryanka>

- src/test/java/old_tests/EnmedvTest.java
testVerifyTextInHeaderH3 refactored, locators and methods added
[RF] - https://trello.com/c/tzojAdRK/582-rfimpressummainheader-verify-text-in-header-h3-enmedv
> [RF][Impressum][main][header] Verify text in header h3 <Enmedv>

- src/test/java/pages/MainPage.java
- src/test/java/pages/SubmitNewLanguagePage.java
- src/test/java/tests/SubmitNewLanguageTest.java
[RF] -  https://trello.com/c/URgTwWmr/630-rfpommainsubmitnewlanguagetesterrormessagesubmitlanguagebuttonalbina-star
> [RF][POM][Main][SubmitNewLanguage]testErrorMessageSubmitLanguageButton<Albina-star>

- src/test/java/old_tests/Yuliya14Test.java
- src/test/java/pages/GuestBookV2Page.java
- src/test/java/tests/GuestBookV2Test.java
testMainNavigationButtonGuestbook_POM_CreatePage, refactored test
[RF] - https://trello.com/c/JJwp9JZS/625-rfpomprojectmainnavigationmenuguestbookv2-click-button-guestbookv2-yuliya14
> [RF][POM][Project][Main][navigation][menu][guestbookv2] click button guestbookv2 <Yuliya14>

- src/test/java/old_tests/NataliiaOliverTest.java
- src/test/java/pages/BasePage.java
- src/test/java/pages/MainPage.java
- src/test/java/pages/StartSubmenuPage.java
- src/test/java/pages/TeamPage.java
- src/test/java/tests/TeamTest.java
POM Refactoring BasePage, MainPage, StartSubmenuPage, TeamPage, RF methods and locators, changed NataliiaOliverTest
[RF] - https://trello.com/c/W9xHCImL/631-rfpomprojectstartnavigationsubmenuteam-refactoring-pages-methods-locatorsnataliiaoliver
> [RF][POM][Project][Start][navigation][submenu][team] Refactoring pages, methods, locators<NataliiaOliver>

- src/test/java/pages/BPage.java
- src/test/java/pages/BashLanguagePage.java
- src/test/java/pages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/MainPage.java
- src/test/java/tests/BashLanguageTest.java
refactoring to POM
added testVerifyingFooterChoosingLanguage()
class BashLanguagePage
class BPage
deleted MaxIasko99Test.java
[US] - https://trello.com/c/JzsCoKDy/615-usstructureproject-createpomprojectstructuremaxiasko
[RF] - https://trello.com/c/JOpoSpcJ/620-rfstructureprojectpomrefactoringprojectstructureiaskomax
[AT] - https://trello.com/c/tO0n8ou3/619-atstructureprojectpomcreatepombaseclassespageclassesmethodslocators-iaskomax
> [AT][Structure][Project][POM]createPOMBaseClassesPageClassesMethodsLocators <IaskoMax>

- src/test/java/pages/AlertPage.java
- src/test/java/pages/FormPage.java
- src/test/java/pages/GuestBookV2Page.java
- src/test/java/pages/MainPage.java
- src/test/java/pages/SignV2Page.java
- src/test/java/tests/SignV2Test.java
[RF][POM] - https://trello.com/c/gEA0qMIT/585-atmainnavigationmenuguestbookv2testsignguestbookverifytextinalerturlandacceptalert-ekaterinalizina)
> [RF][POM][navigation][menu][guestboov2]POM_testSignGuestBookVerifyTextInAlertUrl_ekaterinalizina

- src/test/java/pages/SubmitNewLanguagePage.java
- src/test/java/tests/SubmitNewLanguageTest.java
RFtestVerifyH2HeaderTest_SubmitNewLanguage()_POM
[RF]-https://trello.com/c/o6OhBN2R/632-rfsubmitnewlanguagemainheaderh2testverifyheadertextpomelenakud
> [RF][Submitnewlanguage][main][header][h2]test_VerifyHeaderText_POM<ElenaKud>

- src/test/java/old_tests/NstzyaTest.java
- src/test/java/pages/BPage.java
- src/test/java/pages/BrowseLanguagesSubmenuPage.java
- src/test/java/tests/BTest.java
- src/test/java/tests/BrowseLanguagesSubmenuTest.java
testH2Header() refactored, old test ignored
[RF] - https://trello.com/c/HMNAi2KO/638-rfbmainheaderh2-testh2header-nstzya
> [RF][B][main][header][h2] testH2Header() <Nstzya>

- src/test/java/pages/BPage.java
- src/test/java/pages/BrowseLanguagesSubmenuPage.java
- src/test/java/tests/ABCTest.java
- src/test/java/tests/BTest.java
Reverts RedRoverSchool/AutomationQA_05#300
This PR did not receive the required approval
> Revert "[AT][Structure][Project][POM]CreateABCTestBTestMethodsWebElements<IrynaDanilevska>"

- src/test/java/old_tests/NataliiaOliverTest.java
- src/test/java/pages/TeamPage.java
- src/test/java/tests/TeamTest.java
Refactoring NataliiOliverTest testTeamNames() modificated to POM3
[RF] - https://trello.com/c/djGWNYkx/642-rfpomprojectstartnavigationsubmenuteam-refactoring-testteamnamesnataliiaoliver
> [RF][POM][Project][Start][navigation][submenu][team] Refactoring testTeamNames()<NataliiaOliver>

- src/test/java/pages/ImpressumPage.java
- src/test/java/pages/StartSubmenuPage.java
- src/test/java/tests/ImpressumTest.java
testTextInHeaderH2 created in POM
[RF] - https://trello.com/c/ZzdmaN1I/644-rfimpressummainheader-testtextinheaderh2-pom-enmedv
> [RF][Impressum][main][header] testTextInHeaderH2() POM <Enmedv>

- src/test/java/pages/BasePage.java
- src/test/java/pages/TopListEsotericPage.java
- src/test/java/pages/TopListRealPage.java
- src/test/java/pages/TopListsSubmenuPage.java
- src/test/java/tests/TopListEsotericTest.java
[RF][POM] - https://trello.com/c/lKFdFldp/641-rf-pr-name-github-username
> [RF][POM][Main][navigation][menu][toplist] testTheMostRatedRealLanguageIsDifferFromMostRatedEsotericLanguage_ekaterinalizina

- src/test/java/pages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/MPage.java
- src/test/java/tests/MTest.java
testClickLetterInSubmenu_HappyPath() refactored using POM
[RF] - https://trello.com/c/ixwMYcgS/656-rfabcnavigationsubmenum-testclickletterinsubmenuhappypath-refactored-mariannaliss
> [RF][ABC][navigation][submenu][m] Refactoring pages, methods, locators <MariannaLiss>

- src/test/java/pages/SubmitNewLanguagePage.java
- src/test/java/tests/SubmitNewLanguageTest.java
RF POM of testPleaseNoteItemsQuantity() added
[RF] - https://trello.com/c/o65FZaLd/660-rfpomsubmit-new-languageplease-notetestpleasenoteitemsquantity-albina-star
> [RF][POM][Submit New Language][Please note]testPleaseNoteItemsQuantity() <Albina-star>

- src/test/java/pages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/DPage.java
- src/test/java/tests/DTest.java
testABCNavigationSubmenuLetterD_added
[AT] - https://trello.com/c/7LMFC1Fa/658-atabcnavigationsubmenud-testabcnavigationsubmenuletterd-anastassiai
> [AT][ABC][Navigation][Submenu][d] testABCNavigationSubmenuLetterD <AnastassiaI>

- src/test/java/tests/StartTest.java
testClickStartFromHomepage refactored using POM
[RF][POM] - https://trello.com/c/uhmdyZt4/245-atfunctionalmainnavigationmenustart-testclickstartfromhomepagehappypath
> [RF][POM][navigation][menu][start] testClickStartFromHomepage()

- src/test/java/pages/TeamPage.java
- src/test/java/tests/TeamTest.java
testH2Header()refactored using POM
[RF]  -https://trello.com/c/QPoJfizK/662-rfpomteammainheaderh2-testh2header-yulyanyu
> [RF][POM][Team][main][header][h2] testH2Header <YulyaNyu>

- src/test/java/tests/ABCTest.java
testTextABC added
[AT] - https://trello.com/c/brxLfWVM/643-atmainnavigationmenuabcpom-abc-verify-textirinadud
> [AT][POM][Main][navigation][menu][abc]ABCtext<IrinaDud>

- src/test/java/pages/BasePage.java
- src/test/java/pages/MainPage.java
- src/test/java/tests/MainTest.java
added testMainMenuURLEqualsFooterMenu()
[AT] - https://trello.com/c/7eJbgQHI/645-atmainnavigationmenuabcpomtestmainmenuurlequalsfootermenumaxiasko
added Locators, Methods to MainPage
added method to BasePage
> [AT][Main][Navigation][Menu][Abc][POM]testMainMenuURLEqualsFooterMenu<MaxIasko>

- src/test/java/pages/ImpressumPage.java
- src/test/java/tests/ImpressumTest.java
testTextInHeaderH3 created in POM, locators and methods added
[RF] - https://trello.com/c/FmCLiFEA/664-rfimpressummainheader-testtextinheaderh3-enmedv
> [RF][Impressum][main][header] testTextInHeaderH3() <Enmedv>

- src/test/java/old_tests/GoryankaTest.java
testSearchForLanguageByName_HappyPath re
factored, locators and methods were added
https://trello.com/c/hUrOTaoe/651-rfsearchform-testsearchforlanguagebynamehappypath-goryanka
> [RF][Search][Form] testSearchForLanguageByName_HappyPath() <Goryanka>

- src/test/java/pages/BasePage.java
- src/test/java/pages/BashLanguagePage.java
- src/test/java/tests/BashLanguageTest.java
added testBookmarkActive()
added Method, Locator for BashLanguagePage
added Method for BasePag
[AT] - https://trello.com/c/6CUVoR3n/663-atpombashlanguagepagetestbookmarkactivemaxiasko
> [AT][POM][BashLanguagePage]testBookmarkActive()<MaxIasko>

- src/test/java/pages/JPage.java
- src/test/java/pages/JavaScriptLanguagePage.java
- src/test/java/tests/JavaScriptLanguageTest.java
testJavaScriptLanguagePageHeader() added 
Pages created: JavaScriptLanguagePage
Pages changed : JPage
[AT] - https://trello.com/c/ABIRCXq3/668-atpomlanguagejavascript1948maintableh2-testjavascriptlanguagepageheaderpom-verafes
> [AT][POM][LanguageJavascript1948][main][table][H2] testJavaScriptLanguagePageHeader() <verafes>

- src/test/java/tests/StartTest.java
testClickStartFromSearchLanguagesMenu refactored using POM
[RF][POM] - https://trello.com/c/FJWSFnNW/244-atfunctionalmainnavigationmenustart-testclickstartfromsearchlanguagesmenuhappypathsvetakhudova
> [RF][POM][navigation][menu][start] testClickStartFromSearchLanguagesMenu() <SvetaKhudova>

- src/test/java/pages/BasePage.java
- src/test/java/pages/JPage.java
- src/test/java/pages/JQueryLanguagePage.java
- src/test/java/tests/JQueryLanguageTest.java
- src/test/java/tests/JTest.java
- src/test/java/tests/MainTest.java
testJQueryLink_NavigatesTo_JQueryLanguagePage() created
> [AT][ABC][Navigation][Submenu][J] Navigate To JQueryLanguage test <Lessons>

- src/test/java/old_tests/MaxIasko99Test.java
- src/test/java/pages/browse_languages/letters/BPage.java
- src/test/java/pages/guest_book/SignV2Page.java
- src/test/java/tests/SignV2Test.java
[RF][POM]- https://trello.com/c/ETrxq5Xr/671-rf-pr-name-github-username
> [RF][POM][Main][navigation][menu][guestbookv2] testErrorMessageIfSubmitWithoutCaptcha <ekaterinalizina>

- src/test/java/tests/SearchLanguagesTest.java
RFSearchform_testSearchForLanguagesNameJava_AndEmpty_nikolaymarkov3 added
[RF][POM] - https://trello.com/c/ZqRfd40k/674-rfpomsearchform-testsearchforlanguagesnamejavahappypath-nikolaymarkov3
> [RF][POM][Search][form] testSearchForLanguagesNameJava_HappyPath() <nikolaymarkov3>

- src/test/java/tests/TopListsTest.java
RF testH2HeaderText() to POM
[RF] - https://trello.com/c/G58eFFYq/676-rfpomtoplistmainh2-testh2headertext-anastasiayy
> [RF][POM][Toplist][main][h2] testH2HeaderText() <AnastasiaYY>

- src/test/java/pages/base_abstract/TablePage.java
- src/test/java/tests/YTest.java
add testTableHeaderNames()
[AT] - https://trello.com/c/buYblJ8z/677-atymaintableth-testtableheadernames-anastasiayy
> [AT][Y][main][table][th] testTableHeaderNames <AnastasiaYY>

- src/test/java/pages/start/HistoryPage.java
- src/test/java/tests/HistoryTest.java
testRegularTextOnHistoryPage_added
[TC] - https://trello.com/c/aPjZzfLX/682-tcinfomaintext-testregulartextonsubmenuinfoanastassiai
[AT] - https://trello.com/c/ZriJF12W/683-atinfomaintext-testregulartextonsubmenuinfoanastassiai
> [AT][Info][main][text] testRegularTextOnSubmenuInfo<AnastassiaI>

- src/test/java/pages/start/StartPage.java
- src/test/java/tests/StartTest.java
refactored testWishesFromTheTeamFirstParagraph()
[RF] - https://trello.com/c/CFMAYrvq/670-rfpomstartmaintext-verifywishesfromtheteam-elenastrat
> [RF][POM][Start][Main][Text] testWishesFromTheTeamFirstParagraph <ElenaStrat>

- src/test/java/tests/BashLanguageTest.java
refactoring testFooterChoosingLanguageBASH()
[RF] - https://trello.com/c/HrjBHIUI/679-rfpombashlanguagepagetestfooterchoosinglanguagebashmaxiasko
> [RF][POM][BashLanguagePage]testFooterChoosingLanguageBASH()<MaxIasko>

- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/browse_languages/languages/LuaLanguagePage.java
- src/test/java/pages/browse_languages/letters/LPage.java
- src/test/java/tests/LuaLanguageTest.java
testLuaLanguageLink_NavigatesTo_LuaLanguagePage added, created methods and locators
[AT] - https://trello.com/c/kvQhW5jy/688-atabcnavigationsubmenul-testlualanguagelinknavigatestolualanguagepagealeksandrakimovchg
> [AT][ABC][navigation][submenu][L] testLuaLanguageLink_NavigatesTo_LuaLanguagePage()<AleksandrAkimovChg>

- src/test/java/pages/start/TeamPage.java
- src/test/java/tests/TeamTest.java
Created testTwoImagesOfTeamCreators() and method, loc added
[TC] - https://trello.com/c/xlC42k7c/692-tcstartnavigationsubmenuteam-verify-that-the-number-of-site-creators-images-on-the-team-page-is-two-nataliiaoliver
[AT] - https://trello.com/c/VCzGFZkx/693-atstartnavigationsubmenuteam-testtwoimagesofteamcreators-nataliiaoliver
> [AT][Start][navigation][submenu][team] testTwoImagesOfTeamCreators() <NataliiaOliver>

- src/test/java/pages/browse_languages/languages/YabasicLanguagePage.java
- src/test/java/pages/browse_languages/letters/YPage.java
- src/test/java/tests/YTest.java
- src/test/java/tests/YabasicLanguageTest.java
add testYabasicLink_NavigatesTo_YabasicLanguagePage()
[AT] - https://trello.com/c/c1rZr0Sm/701-atabcnavigationsubmenuy-testyabasiclinknavigatestoyabasiclanguagepage-anastasiayy
> [AT][ABC][navigation][submenu][Y] testYabasicLink_NavigatesTo_YabasicLanguagePage() <AnastasiaYY>

- src/test/java/pages/start/StartPage.java
- src/test/java/tests/StartTest.java
added testHeaderTextH2 
[AT] - https://trello.com/c/G8oGr4MD/697-atstartmainheaderh2-verify-text-mbatoz
> [AT][Start][main][header][h2] testHeaderTextH2 <mbatoz>

- src/test/java/pages/browse_languages/languages/ShakespeareLanguagePage.java
- src/test/java/pages/browse_languages/languages/WhitespaceLanguage.java
- src/test/java/pages/top_lists/TopHitsPage.java
- src/test/java/pages/top_lists/TopListsSubmenuPage.java
- src/test/java/tests/TopHitsTest.java
- src/test/java/tests/TopListEsotericTest.java
[TC] - https://trello.com/c/5YP8LBT2/699-tctoplistsubmenutophits-testshakespearelinknavigatestoshakespearelanguagepage-ekaterinalizina
[AT] -https://trello.com/c/YQQP0lun/700-atpomtoplistsubmenutophits-testshakespearelinknavigatestoshakespearelanguagepage-ekaterinalizina
> [AT][POM][Toplist][submenu][tophits] testShakespeareLink_NavigatesTo_ShakespeareLanguagePage() <ekaterinalizina>

- src/test/java/tests/GuestBookV2Test.java
POM test_MainNavigationMenuButtonGuestbook modification and addition
[RF] - https://trello.com/c/i0IUDv0w/678-rfmainnavigationmenuguestbook-pom-testmainnavigationmenubuttonguestbook-yuliya14
> [RF][POM] test_MainNavigationMenuToButtonGuestbook <Yuliya14>

- src/test/java/tests/SearchLanguagesTest.java
RF_POM_Searchform_ChangingTheTestName_nikolaymarkov3 added
[RF] - https://trello.com/c/n5wApZeE/703-rfpomsearchformchanging-the-test-name-nikolaymarkov3
> [RF][POM][Search][form]Changing the test name <nikolaymarkov3>

- src/test/java/old_tests/VerafesTest.java
- src/test/java/tests/JTest.java
testJavaScriptLink_NavigatesTo_JavaScriptLanguagePage() added
[TC] - https://trello.com/c/ZDCjlykb/704-tcmainnavigationmenusearch-search-for-languages-by-name-javascript-verafes
[AT] - https://trello.com/c/Kv5XdXU3/705-atmainnavigationmenusearch-javascriptlinknavigatestojavascriptlanguagepage-verafes
old class ignored
> [AT][Main][navigation][menu][search] JavaScriptLink_NavigatesTo_JavaScriptLanguagePage() <verafes>

- src/test/java/pages/browse_languages/languages/CheetahLanguagePage.java
- src/test/java/pages/browse_languages/letters/CPage.java
- src/test/java/tests/CTest.java
- src/test/java/tests/CheetahLanguageTest.java
Created pages CheetahLanguagePage, CheetahLanguageTest and testCheetahLink_NavigatesTo_CheetahLanguagePage()added locator and methods
[AT] - https://trello.com/c/Azx1AOdy/711-atabcnavigationsubmenuy-testcheetahlinknavigatestocheetahlanguagepage-nataliiaoliver
> [AT][ABC][navigation][submenu][C] testCheetahLink_NavigatesTo_CheetahLanguagePage() <NataliiaOliver>

- src/test/java/pages/start/HistoryPage.java
- src/test/java/tests/HistoryTest.java
testNumberOfImagesOnHistoryPage_added
[TC] - https://trello.com/c/abtBUXIL/714-tcinfomainimagetestnumberofimagesonhistorypage-anastassiai
[AT] - https://trello.com/c/Z8OAugzM/713-atinfomainimagetestnumberofimagesonhistorypage-anastassiai
> [AT][Info][main][image]testNumberOfImagesOnHistoryPage <AnastassiaI>

- src/test/java/pages/base_abstract/TablePage.java
- src/test/java/tests/JavaScriptLanguageTest.java
testTableListNames() on JS page added 
[AT] - https://trello.com/c/POc1LkZS/717-atlanguagejavascript1948maintabletd-testtablelistnames-verafes
[TC] - https://trello.com/c/Z2B2PrEK/718-tcpomlanguagejavascript1948maintabletd-verify-top-table-list-namesverafes
> [AT][POM][LanguageJavascript1948][main][table][td] testTableListNames() <verafes>

- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/browse_languages/languages/AdaLanguagePage.java
- src/test/java/pages/browse_languages/letters/APage.java
- src/test/java/tests/AdaLanguageTest.java
added AdaLanguageTest.java
APage.java
AdaLanguagePage.java
[TC] - https://trello.com/c/uTEeuz6V/723-tcmainfunctionalitybrowselanguagepom-testchoosinglanguageadamaxiasko
[AT] - https://trello.com/c/Hmq7pEQS/724-atmainfunctionalitybrowselanguagepomtestchoosinglanguageadamaxiasko
> [AT][Main][Functionality][BrowseLanguage][POM]AdaLanguageTest<MaxIasko>

- src/test/java/pages/browse_languages/languages/ZimLanguagePage.java
- src/test/java/pages/browse_languages/letters/ZPage.java
- src/test/java/tests/ZTest.java
testZimLink_NavigatesTo_ZimLanguagePage() added
[TC] -https://trello.com/c/diTtbl1E/716-tcabcnavigationsubmenuz-verify-navigation-to-zim-language-pageelenakud
[AT] -https://trello.com/c/5fRMKjYG/720-atabcnavigationsubmenuz-zimlinknavigatestozimlanguagepageelenakud
> [AT][ABC][navigation][submenu][z] testZimLink_NavigatesTo_ZimLanguagePage()<ElenaKud>

- src/test/java/pages/browse_languages/languages/YacasLanguagePage.java
- src/test/java/pages/browse_languages/letters/YPage.java
- src/test/java/tests/YTest.java
add testYacasLink_NavigatesTo_YacasLanguagePage()
[AT] - https://trello.com/c/g4QFgJWO/728-atabcnavigationsubmenuy-testyacaslinknavigatestoyacaslanguagepage-anastasiayy
> [AT][ABC][navigation][submenu][y] testYacasLink_NavigatesTo_YacasLanguagePage() <AnastasiaYY>

- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/browse_languages/languages/EnglishLanguagePage.java
- src/test/java/pages/browse_languages/letters/EPage.java
- src/test/java/tests/ETest.java
- src/test/java/tests/EnglishLanguageTest.java
Created testEnglishLink_NavigatesTo_EnglishLanguagePage(), added methods and locators
[TC] - https://trello.com/c/wPZrlrjc/729-tcabcnavigationsubmenue-verify-that-english-link-navigets-to-englishlanguagepage-nataliiaoliver
[AT] - https://trello.com/c/17DQL1DU/730-atabcnavigationsubmenue-testenglishlinknavigatestoenglishlanguagepage-nataliiaoliver
> [AT][ABC][navigation][submenu][E] testEnglishLink_NavigatesTo_EnglishLanguagePage() <NataliiaOliver>

- src/test/java/pages/base_abstract/TablePage.java
- src/test/java/tests/JavaScriptLanguageTest.java
testTableListValues() on JS page added
[AT] https://trello.com/c/BwpUIVAA/733-atlanguagejavascript1948maintabletd-testtablelistvalues-verafes
[TC] https://trello.com/c/OwhRjx1l/734-tcpomlanguagejavascript1948maintabletd-verify-top-table-list-valuesverafes
> [AT][LanguageJavascript1948][main][table][td] testTableListValues() <verafes>

- src/test/java/pages/browse_languages/languages/LanguagePage.java
- src/test/java/pages/browse_languages/languages/YacasLanguagePage.java
- src/test/java/tests/YacasLanguageTest.java
add testVotingNiceCodingIsSelected
[AT] - https://trello.com/c/96O8PAAX/731-atlanguage-pagevoting-testvotingnicecodingisselected-anastasiayy
> [AT][Language Page][Voting] testVotingNiceCodingIsSelected <AnastasiaYY>

- src/test/java/pages/base_abstract/MainPage.java
- src/test/java/tests/MainTest.java
testNavigationMenuLinksAmountAndText() was changed to POM
RF - https://trello.com/c/jrBn0HvG/739-rfmainnavigationmenu-testnavigationmenulinksamountandtext-mariayanu
> [RF][Main][navigation][menu] testNavigationMenuLinksAmountAndText () <MariaYanu>

- src/test/java/pages/base_abstract/TablePage.java
- src/test/java/tests/ATest.java
testAPageMostCommentedLanguage() added
[TC] - https://trello.com/c/S82KtTzr/707-tcbrowselanguagesapageapagemostcommentedlanguagemaxiasko
[AT] - https://trello.com/c/V0QQJUkH/708-atbrowselanguagesapageapagemostcommentedlanguagemaxiasko
> [AT][BrowseLanguages][APage]APageMostCommentedLanguage<MaxIasko>

- src/test/java/pages/start/StartSubmenuPage.java
- src/test/java/tests/StartSubmenuTest.java
Created testStartSubmenuButtonsNames(), method and locator
[TC] - https://trello.com/c/HbIVsJVd/746-tcstartnavigationsubmenu-verify-that-all-the-names-on-the-buttons-in-the-startsubmenu-are-displayednataliiaoliver
[AT] - https://trello.com/c/tadcCKHN/747-atstartnavigationsubmenu-teststartsubmenubuttonsnames-nataliiaoliver
> [AT][Start][navigation][submenu] testStartSubmenuButtonsNames() <NataliiaOliver>

- src/test/java/pages/guest_book/GuestBookSubmenuPage.java
- src/test/java/pages/start/StartSubmenuPage.java
- src/test/java/tests/GuestBookSubmenuTest.java
- src/test/java/tests/StartSubmenuTest.java
Guest book navigation submenu all guest book submenu buttons names are displayed
[TC] - https://trello.com/c/aAF6YQXG/748-tcguestbookv2navigationsubmenu-verify-that-all-the-names-on-the-buttons-in-the-guestbooksubmenu-are-displayednataliiaoliver
[AT] - https://trello.com/c/PgBVaLsW/749-atguestbookv2navigationsubmenu-testguestbooksubmenubuttonsnames-nataliiaoliver
> [AT][Guestbookv2][navigation][submenu] testGuestBookSubmenuButtonsNames() <NataliiaOliver>

- src/test/java/pages/base_abstract/TablePage.java
- src/test/java/tests/BTest.java
added testBPageAuthorMostCommentedLanguage()
[TC] - https://trello.com/c/2cgepGyZ/740-tcbrowselanguagesbpageauthormostcommentedlanguagemaxiasko
[AT] - https://trello.com/c/cDw1oy9y/741-atbrowselanguagesbpageauthormostcommentedlanguagemaxiasko
> [AT][BrowseLanguages][BPage]AuthorMostCommentedLanguage<MaxIasko>

- src/test/java/pages/browse_languages/languages/KotlinLanguagePage.java
- src/test/java/tests/KotlinLanguageTest.java
created testKotlinPageContent(), methods and locators
[TC] - https://trello.com/c/k0ALva3x/753-tclanguagekotlinmaintablelink-verify-that-all-content-is-present-on-the-language-page-akeksandrakimovchg
[AT] - https://trello.com/c/k2IJZtlj/755-atlanguagekotlinmaintablelink-testkotlinpagecontentakeksandrakimovchg
> [AT][LanguageKotlin][main][table][link] testKotlinPageContent()<AkeksandrAkimovChg>

- src/test/java/pages/start/StartPage.java
- src/test/java/tests/StartTest.java
Created testTextsWithLinksOnStartPage(), method, locator
[TC] - https://trello.com/c/ParBLQlz/752-tcstartmaintext-verify-that-texts-containing-links-are-displayed-on-the-startpage-nataliiaoliver
[AT] - https://trello.com/c/gtXUSQNZ/754-atstartmaintext-testtextswithlinksonstartpage-nataliiaoliver
> [AT][Start][main][text] testTextsWithLinksOnStartPage() <NataliiaOliver>

- src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
- src/test/java/pages/submit_new_language/SubmitNewLanguageSubmenuPage.java
- src/test/java/tests/SubmitNewLanguageTest.java
testCaptchaErrorMessage added,locators and methods created, SubmitNewLanguageSubmenuPage extended to FormPage
[AT] - https://trello.com/c/iembsmFt/744-atsubmitnewlanguagemaintext-testcaptchaerrormessage-victorialema
> [AT][Submitnewlanguage][main][text] testCaptchaErrorMessage <VictoriaLema>

- src/test/java/tests/MainTest.java
refactoring testMainMenuURLEqualsFooterMenu()
[RF] - https://trello.com/c/aIgOTgyp/758-rfpommainpagetestmainmenuurlequalsfootermenumaxiasko
> [RF][POM][MainPage]testMainMenuURLEqualsFooterMenu()<MaxIasko>

- pom.xml
- src/test/java/network/CaptureNetworkTraffic.java
- src/test/java/pages/search_languages/SearchLanguagesPage.java
- src/test/java/tests/API_SearchLanguagesTest.java
APITests and NetworkCupture Methods added
> APITests and NetworkCupture Methods added <Lesson>

- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
- src/test/java/tests/BrowseLanguagesSubmenuTest.java
testTextAndLinksSubmenu() added and refactored getListSymbolsSubmenuWhenClickTrue()
[AT] - https://trello.com/c/vOtTcslo/756-atabcnavigationsubmenu-testtextandlinkssubmenu-aleksandrakimovchg
> [AT][ABC][navigation][submenu] testTextAndLinksSubmenu() <AleksandrAkimovChg>

- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/browse_languages/letters/JPage.java
- src/test/java/tests/API_JTest.java
test_API_HttpRequest_GET() and test_API_HttpResponse_GET() added
API tests for Navigation to JPage 
[AT] - https://trello.com/c/eI46qWrC/761-atapiabcnavigationsubmenuj-testapihttpresponsegetverafes
> [AT][API][ABC][navigation][submenu][J] test_API_HttpResponse_GET<verafes>

- src/test/java/pages/start/StartPage.java
- src/test/java/tests/StartTest.java
Created testHistoricInformationLink_NavigatesTo_HistoryPage(), methods and locators
[TC] - (https://trello.com/c/cHGIZ0e5/762-tcstartnavigation-verify-that-historicinformation-link-navigates-to-historypage-nataliiaoliver)
[AT] - https://trello.com/c/gsmXwvJm/767-atstartnavigation-testhistiricinformationlinknavigatestohistorypage-nataliiaoliver
> [AT][Start][navigation] testHistiricInformationLink_NavigatesTo_HistoryPage <NataliiaOliver>

- src/test/java/tests/TeamTest.java
Changed name testETasteOrgLink_NavigatesTo_ExternalGregorScheithauer(), added title verify
[RF] - https://trello.com/c/HTWXR800/773-rfstartnavigationsubmenuteam-testetasteorglinknavigatestoexternalgregorscheithauernataliiaoliver
> [RF][Start][navigation][submenu][team] testETasteOrgLink_NavigatesTo_ExternalGregorScheithauer()<NataliiaOliver>

- src/test/java/pages/start/StartPage.java
- src/test/java/tests/StartTest.java
Created testHereLink_NavigatesTo_LyricsPage(), added method and locator
[TC] - https://trello.com/c/NmrdSdUb/763-tcstartnavigation-verify-that-here-link-navigates-to-lyricspage-nataliiaoliver
[AT] - https://trello.com/c/kLWvGGFU/768-atstartnavigation-testherelinknavigatestolyricspage-nataliiaoliver
> [AT][Start][navigation] testHereLink_NavigatesTo_LyricsPage()<NataliiaOliver>

- src/test/java/pages/start/StartPage.java
- src/test/java/tests/StartTest.java
Created testSubmitYourOwnPieceofCodeLink_NavigatesTo_SubmitNewLanguagePage(), added method and locator
[TC] - https://trello.com/c/1QT4XNcV/764-tcstartnavigation-verify-that-submityourownpieceofcode-link-navigates-to-submitnewlanguagepage-nataliiaoliver
[AT] - https://trello.com/c/8PwlGMFS/769-atstartnavigation-testsubmityourownpieceofcodelinknavigatestosubmitnewlanguagepage-nataliiaoliver
> [AT][Start][navigation] testSubmitYourOwnPieceofCodeLink_NavigatesTo_SubmitNewLanguagePage() <NataliiaOliver>

- src/test/java/pages/start/StartPage.java
- src/test/java/tests/StartTest.java
Created testGuestbookLink_NavigatesTo_GuestbookV2Page(), method and locator added
[TC] - https://trello.com/c/7vbwMr5P/765-tcstartnavigation-verify-that-guestbook-link-navigates-to-guestbookv2page-nataliiaoliver 
[AT] - https://trello.com/c/G2XDmjHd/770-atstartnavigation-testguestbooklinknavigatestoguestbookv2page-nataliiaoliver
> [AT][Start][navigation] testGuestbookLink_NavigatesTo_GuestbookV2Page() 

- src/test/java/pages/start/StartPage.java
- src/test/java/tests/StartTest.java
Created testTeamMembersLink_NavigatesTo_TeamPage(), method and locator added
[TC] - https://trello.com/c/NQu3J6nl/766-tcstartnavigation-verify-that-teammembers-link-navigates-to-teampage-nataliiaoliver
[AT] - https://trello.com/c/dxIPkUSL/771-atstartnavigation-testteammemberslinknavigatestoteampage-nataliiaoliver
> [AT][Start][navigation] testTeamMembersLink_NavigatesTo_TeamPage() <NataliiaOliver>

- src/test/java/tests/StartTest.java
- src/test/java/tests/TeamTest.java
Changed name of testStsSynfloodDe_NavigatesTo_ExternalStefanScheler(), added title verify
[RF] - https://trello.com/c/ihT8YTkz/774-rfstartnavigationsubmenuteam-teststssynflooddenavigatestoexternalstefanschelernataliiaoliver
> [RF][Start][navigation][submenu][team] testStsSynfloodDe_NavigatesTo_ExternalStefanScheler()<NataliiaOliver>

- src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
SubmitNewLanguage code cleaned
> SubmitNewLanguage code cleaned

- src/test/java/pages/browse_languages/languages/LanguagePage.java
- src/test/java/tests/KotlinLanguageTest.java
- src/test/java/tests/browse_languages/ABCTest.java
- src/test/java/tests/browse_languages/BrowseLanguagesSubmenuTest.java
- src/test/java/tests/browse_languages/languages/AdaLanguageTest.java
- src/test/java/tests/browse_languages/letters/ATest.java
- src/test/java/tests/browse_languages/letters/BTest.java
- src/test/java/tests/guest_book/GuestBookSubmenuTest.java
- src/test/java/tests/search_languages/SearchLanguagesTest.java
- src/test/java/tests/start/HistoryTest.java
- src/test/java/tests/submit_new_language/SubmitNewLanguageSubmenuTest.java
- src/test/java/tests/top_lists/TopHitsTest.java
new structure for tests package created
> New structure for tests package created

- src/test/java/tests/browse_languages/languages/BashLanguageTest.java
- src/test/java/tests/browse_languages/languages/CheetahLanguageTest.java
- src/test/java/tests/browse_languages/languages/DelphiLanguageTest.java
- src/test/java/tests/browse_languages/languages/EnglishLanguageTest.java
- src/test/java/tests/browse_languages/languages/JQueryLanguageTest.java
- src/test/java/tests/browse_languages/languages/JavaLanguageTest.java
- src/test/java/tests/browse_languages/languages/JavaScriptLanguageTest.java
- src/test/java/tests/browse_languages/languages/KotlinLanguageTest.java
- src/test/java/tests/browse_languages/languages/LuaLanguageTest.java
- src/test/java/tests/browse_languages/languages/PythonLanguageTest.java
- src/test/java/tests/browse_languages/languages/YabasicLanguageTest.java
- src/test/java/tests/browse_languages/languages/YacasLanguageTest.java
- src/test/java/tests/guest_book/GuestBookV2Test.java
- src/test/java/tests/guest_book/SignV2Test.java
- src/test/java/tests/start/LyricsTest.java
- src/test/java/tests/start/PrivacyTest.java
- src/test/java/tests/start/StartSubmenuTest.java
- src/test/java/tests/start/StartTest.java
- src/test/java/tests/start/TeamTest.java
- src/test/java/tests/submit_new_language/SubmitNewLanguageTest.java
- src/test/java/tests/top_lists/NewCommentsTest.java
- src/test/java/tests/top_lists/TopListAssemblyTest.java
- src/test/java/tests/top_lists/TopListEsotericTest.java
- src/test/java/tests/top_lists/TopListNewLanguagesThisMonthTest.java
- src/test/java/tests/top_lists/TopListRealTest.java
- src/test/java/tests/top_lists/TopListsSubmenuTest.java
- src/test/java/tests/top_lists/TopListsTest.java
> Moved tests to testPacages

- src/test/java/tests/start/HistoryTest.java
- src/test/java/tests/start/LyricsTest.java
> Refactoring SrartTest

- src/test/java/tests/api/API_TopListSubmenuTest.java
[AT] - https://trello.com/c/Qfb3TnfU/780-atapimaintoplistsubmenu-apitoplistsubmenutest-albinastar
> [AT][API][Main][TopListSubmenu]API_TopListSubmenuTest<Albina_star>

- src/test/java/pages/browse_languages/languages/EnglishLanguagePage.java
- src/test/java/tests/browse_languages/languages/EnglishLanguageTest.java
testFormLinkNavigatesToSubmitNewLanguagePage(), locators and methods created
[AT] - https://trello.com/c/uqLC8wVh/781-atlanguageenglishnavigation-testformlinknavigatestosubmitnewlanguagepage-victorialema
> [AT][LanguageEnglish][navigation] testFormLinkNavigatesToSubmitNewLanguagePage <VictoriaLema>

- src/test/java/old_tests/NstzyaTest.java
- src/test/java/tests/api/API_StartTest.java
test_API_AllLinksInsideMainAreNotBroken() added, the rest of my old_tests ignored
[AT] - https://trello.com/c/MVeGTTgH/785-atapistartmainlink-testapialllinksinsidemainarenotbroken-nstzya
> [AT][API][Start][Main][Link] test_API_AllLinksInsideMainAreNotBroken <Nstzya>

- src/test/java/pages/top_lists/TopListsSubmenuPage.java
- src/test/java/tests/api/API_TopRatedRealTest.java
[AT] - https://trello.com/c/UmxKtpsC/783-atapitoplistsubmenutopratedreal-apitopratedrealtest-albinastar
> [AT][API][TopListSubmenu][TopRatedReal]API_TopRatedRealTest <Albina_star>

- src/test/java/tests/browse_languages/letters/ZTest.java
testH2TextPageZ added
AT - https://trello.com/c/QeWaMBrn/721-atpommainfooterabcz-testh2text-andreimironau
> [AT][POM][Main][footer][abc][Z] testH2Header() <AndreiMironau>

- src/test/java/pages/browse_languages/languages/KalkulonLanguagePage.java
- src/test/java/pages/browse_languages/letters/KPage.java
- src/test/java/tests/browse_languages/languages/KalkulonLanguageTest.java
testKalkulonLanguagePageHeader() added
KalkulonLanguagePage and KalkulonLanguageTest created
[AT] - https://trello.com/c/dU7eN5db/787-atlanguagekalkulon740pagemainheadertext-testkalkulonlanguagepageheader-natalliaowl
> [AT][LanguageKalkulon740Page][main][header][text] testKalkulonLanguagePageHeader() <NatalliaOwl>

- src/test/java/pages/top_lists/TopListsSubmenuPage.java
- src/test/java/tests/api/API_TopHitsTest.java
testAttributes_DefaultValuesTopHits() added
[AT] - https://trello.com/c/yX6TWp4h/786-atapitopliststophits-testattributesdefaultvaluestophits-albinastar
> [AT][API][TopLists][TopHits]testAttributes_DefaultValuesTopHits()<Albina_star>

- src/test/java/tests/browse_languages/letters/KTest.java
testKalkulonLink_NavigatesTo_KalkulonLanguagePage() added
[AT] - https://trello.com/c/JO0UHsgb/782-atabcnavigationsubmenukkalkulonlanguagepage-testkalkulonlinknavigatestokalkulonlanguagepage-natalliaowl
> [AT][ABC][navigation][submenu][k][KalkulonLanguagePage] testKalkulonLink_NavigatesTo_KalkulonLanguagePage() <NatalliaOwl>

- src/test/java/pages/MainTest.java
- src/test/java/pages/base_abstract/FormPage.java
- src/test/java/pages/base_abstract/MainPage.java
- src/test/java/pages/base_abstract/TablePage.java
- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/guest_book/GuestbookSubmenuPage.java
- src/test/java/pages/search_languages/SearchLanguagesSubmenuPage.java
- src/test/java/pages/start/StartSubmenuPage.java
- src/test/java/pages/submit_new_language/SubmitNewLanguageSubmenuPage.java
- src/test/java/pages/top_lists/TopListsSubmenuPage.java
Generic Type created and used in tests
> Generic Type created and used in tests <Lessons>

- src/test/java/pages/base_abstract/MainPage.java
- src/test/java/pages/start/LyricsPage.java
- src/test/java/tests/start/LyricsTest.java
- src/test/java/utils/TestUtils.java
test99BottlesSongLyrics() added
> test99BottlesSongLyrics() added <Lessons>

- src/test/java/old_tests/AnzhelikaBaaTest.java
- src/test/java/tests/api/API_KotlinLanguageTest.java
added tests:
test_API_AllLanguagesLinksAreNotBroken() 
test_API_AllImagesAreNotBroken()
[AT] - https://trello.com/c/33T5ZR8N/788-atlanguagekotlinmain-testapiallimagesarenotbroken-akeksandrakimovchg
> [AT][LanguageKotlin][main] test_API_AllImagesAreNotBroken() <AkeksandrAkimovChg>

- src/test/java/pages/base_abstract/TablePage.java
added if for index 0
- https://github.com/RedRoverSchool/AutomationQA_05/pull/428#issuecomment-1356273502
[RF] - https://trello.com/c/YQ9NWAoT/790-rfymaintablelink-testrandomlinknavigatestocorrespondingpage-aleksandrakimovchg
> [RF][Y][main][table][link] testRandomLinkNavigatesToCorrespondingPage() <AleksandrAkimovChg>

- src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
- src/test/java/tests/submit_new_language/SubmitNewLanguageTest.java
Created testIncludesLanguageCategory(), added locator and method
[TC] - https://trello.com/c/1avztNOW/794-tcsubmitnewlanguagemaintext-verify-that-category-field-contains-3-languagesnataliiaoliver
[AT] - https://trello.com/c/b1cKUA83/795-atsubmitnewlanguagemaintext-testincludeslanguagecategory-nataliiaoliver
> [AT][Submitnewlanguage][main][text] testIncludesLanguageCategory() <NataliiaOliver>

- src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
Added private static final String SUBMIT_NEW_LANGUAGE_PAGE_CATEGORY_PATH for locators optimization
[RF] - https://trello.com/c/Um1UudEa/796-rfsubmitnewlanguagemaintext-xpath-optimization-in-the-submitnewlanguagepage-for-the-category-nataliiaoliver
> [RF][Submitnewlanguage][main][text] XPath optimization in the SubmitNewLanguagePage for the Category <NataliiaOliver>

- src/test/java/tests/search_languages/SearchLanguagesTest.java
testTwoCharactersInputReturnsLanguageListWithThoseCharacters added
[AT] - https://trello.com/c/ppohV4iL/797-atsearchform-testtwocharactersinputreturnslanguageslistwiththosecharacters-katy313
> [AT][Search][form] testTwoCharactersInputReturnsLanguagesListWithThoseCharacters_katy1313

- src/test/java/TestData/TestData.java
- src/test/java/tests/browse_languages/languages/BashLanguageTest.java
added testBookmarkingNavigateToCorrespondingPage
[AT] - https://trello.com/c/2WFzjevc/798-atsearchbashlanguagepage-testbookmarkingnavigatetocorrespondingpagemaxiasko
> [AT][Search][BashLanguagePage] testBookmarkingNavigateToCorrespondingPage <MaxIasko>

- src/test/java/pages/browse_languages/languages/MagnumLanguagePage.java
- src/test/java/pages/browse_languages/letters/MPage.java
- src/test/java/tests/api/API_MagnumLanguageTest.java
APINetworkCapture_API_MagnumLanguageTests added
[AT] - https://trello.com/c/N2vSWESg/801-atapinetworkcapture-apimagnumlanguagetest-nstzya
> [AT][API][NetworkCapture] API_MagnumLanguageTest <Nstzya>

- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
- src/test/java/pages/browse_languages/languages/ScalaLanguagePage.java
- src/test/java/pages/browse_languages/letters/JPage.java
- src/test/java/pages/browse_languages/letters/SPage.java
- src/test/java/tests/browse_languages/languages/ScalaLanguageTest.java
- src/test/java/tests/browse_languages/letters/STest.java
testScalaLink_NavigatesTo_ScalaLanguagePage created
[AT] - https://trello.com/c/0xUDDSaT/802-atmainnavigationmenusearch-scalalinknavigatestoscalalanguagepage-enmedv
> [AT][Main][navigation][menu][search] ScalaLink_NavigatesTo_ScalaLanguagePage <Enmedv>

- src/test/java/tests/api/API_JavaScriptLanguageTest.java
API tests_LanguageJavascript are added
[AT][API] - https://trello.com/c/5bi2gZeD/804-atapinetworkcapture-apitestlanguagejavascript-verafes
> [AT][API][NetworkCapture] API_test_LanguageJavascript <verafes>

- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
added letters locaros for BrowseLanguagesSubmenuPage
[US][Structure] - https://trello.com/c/woSbNmVq/806-usstructurebrowselanguagessubmenupage-create-locatorsaleksandrakimovchg
> [US][Structure][BrowseLanguagesSubmenuPage] create locators<AleksandrAkimovChg>

- src/test/java/pages/base_abstract/MainPage.java
- src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
- src/test/java/tests/submit_new_language/SubmitNewLanguageTest.java
Created testImportantText() and testImportantTextFontAndColors(), added loc and methods
I send 2 tests to this PR, they are logically connected
[TC] - https://trello.com/c/8FWqr4Vd/809-tcsubmitnewlanguagemainform-verify-the-important-text-nataliiaoliver
[AT] - https://trello.com/c/C3cmcJ6B/810-atsubmitnewlanguagemainform-testimportanttext-nataliiaoliver
[TC] - https://trello.com/c/vg9msgRz/808-tcsubmitnewlanguagemainform-verify-the-style-attributes-of-important-text-nataliiaoliver
[AT] - https://trello.com/c/ABbcEOLg/811-atsubmitnewlanguagemainform-testimportanttextfontandcolors-nataliiaoliver
> [AT][Submitnewlanguage][main][form] testImportantText() <NataliiaOliver>

- src/test/java/pages/base_abstract/MainPage.java
- src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
- src/test/java/tests/submit_new_language/SubmitNewLanguageTest.java
Reverts RedRoverSchool/AutomationQA_05#446
> Revert "[AT][Submitnewlanguage][main][form] testImportantText() <NataliiaOliver>"

- src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
Reverts RedRoverSchool/AutomationQA_05#445
> Revert "[US][Structure][BrowseLanguagesSubmenuPage] create locators<AleksandrAkimovChg>"

- src/test/java/tests/browse_languages/letters/YTest.java
CI checked after multiple reverts
> CI checked after multiple reverts

- src/test/java/TestData/TestData.java
- src/test/java/pages/top_lists/TopListsSubmenuPage.java
- src/test/java/tests/top_lists/TopListsSubmenuTest.java
added testSubMenuLinksNavigateToCorrespondingPages
[AT]-https://trello.com/c/L4XB3qbQ/813-atabctoplistsubmenu-testsubmenulinksnavigatetocorrespondingpages-maxiasko
> [AT][ABC][TopList][submenu] testSubMenuLinksNavigateToCorrespondingPages <MaxIasko>

- src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
- src/test/java/tests/api/API_SubmitNewLanguageTest.java
API_SubmitNewLanguageTest created,tests in API_SubmitNewLanguageTest, locators and methods added
[AT]-https://trello.com/c/Xjh8JHfT/815-atapisubmitnewlanguage-main-apisubmitnewlanguage-victorialema
> [AT][API][SubmitNewLanguage ][main] API_SubmitNewLanguage <VictoriaLema>

- src/test/java/tests/browse_languages/BrowseLanguagesSubmenuTest.java
testFooterLetterSubmenusNavigateToCorrespondingPages added
[AT][ABC][navigation][submenu]testFooterLetterSubmenusNavigateToCorrespondingPages - https://trello.com/c/9CQ4Gl7D/814-atabcnavigationsubmenutestfooterlettersubmenusnavigatetocorrespondingpagesanzhelikabaa
> [AT][ABC][navigation][submenu]testFooterLetterSubmenusNavigateToCorrespondingPages() AnzhelikaBaa

- src/test/java/TestData/TestData.java
- src/test/java/pages/start/StartSubmenuPage.java
- src/test/java/tests/start/StartSubmenuTest.java
testFooterStartSubmenusNavigateToCorrespondingPages() added
[AT] - https://trello.com/c/A24rapVo/816-atstartnavigationsubmenu-testfooterstartsubmenusnavigatetocorrespondingpages-nstzya
> [AT][Start][navigation][submenu] testFooterStartSubmenusNavigateToCorrespondingPages <Nstzya>

- README.md
Please do your comments and suggestions
> ReadMe file added

- src/test/java/tests/api/API_TopListRealTest.java
API_TopListRealTests added
[AT] - https://trello.com/c/rqibArVV/817-atapinetworkcapture-apitesttoplistreal-verafes
> [AT][API][NetworkCapture] API_test_TopListReal <verafes>

- src/test/java/TestData/TestData.java
- src/test/java/pages/base_abstract/BasePage.java
- src/test/java/pages/search_languages/SearchLanguagesSubmenuPage.java
- src/test/java/tests/search_languages/SearchLanguagesSubmenuTest.java
added test with dataprovider for searchLanguagesSubmenu
[AT] - https://trello.com/c/EcRXECOn/818-atsearchsubmenu-dataprovider-for-submenu-in-search-languages-menu-aleksandrakimovchg
> [AT][Search][Submenu] dataprovider for submenu in Search Languages menu <AleksandrAkimovChg>

- src/test/java/TestData/TestData.java
- src/test/java/pages/guest_book/GuestbookSubmenuPage.java
- src/test/java/tests/guest_book/GuestBookSubmenuTest.java
add testGuestbookSubmenuNavigatesToCorrespondingPages
[AT] - https://trello.com/c/ygdc9tVv/820-atguestbooksubmenu-dataprovider-for-submenu-anastasiayy
> [AT][Guestbook][Submenu] dataprovider for submenu <AnastasiaYY>

- src/test/java/TestData/TestData.java
- src/test/java/pages/start/StartSubmenuPage.java
- src/test/java/tests/start/StartSubmenuTest.java
- src/test/java/tests/top_lists/TopListRealTest.java
Created testStartSubmenuNavigateToCorrespondingPages, added locator and methods
[AT] - https://trello.com/c/N9YMx9WZ/824-atstartsubmenu-teststartsubmenunavigatetocorrespondingpages-nataliiaoliver
> [AT][Start][Submenu] testStartSubmenuNavigateToCorrespondingPages <NataliiaOliver >

- src/test/java/tests/browse_languages/languages/KotlinLanguageTest.java
corrected a typo
[RF] - https://trello.com/c/xdZLhVUt/825-rf-kotlinlanguagetest-aleksandrakimovchg
> [RF] KotlinLanguageTest <AleksandrAkimovChg>

- src/test/java/tests/API_SearchLanguagesTest.java
removed unused class API_SearchLanguagesTest
[RF] - https://trello.com/c/NWWrxjvh/826-rf-removed-unused-class-apisearchlanguagestest-aleksandrakimovchg
> [RF] removed unused class API_SearchLanguagesTest <AleksandrAkimovChg>

- src/test/java/testData/TestData.java
- src/test/java/tests/MainTest.java
- src/test/java/tests/browse_languages/BrowseLanguagesSubmenuTest.java
- src/test/java/tests/browse_languages/languages/BashLanguageTest.java
- src/test/java/tests/guest_book/GuestBookSubmenuTest.java
- src/test/java/tests/search_languages/SearchLanguagesSubmenuTest.java
- src/test/java/tests/start/StartSubmenuTest.java
- src/test/java/tests/submit_new_language/SubmitNewLanguageSubmenuTest.java
- src/test/java/tests/top_lists/TopListsSubmenuTest.java
rename package TestData to testData
[RF] - https://trello.com/c/nko7jX2W/827-rf-rename-package-testdata-to-testdata-aleksandrakimovchg
> [RF] rename package TestData to testData <AleksandrAkimovChg>

- src/test/java/tests/guest_book/SignGuestbookTest.java
testTextInMessageField_WhenClickSubmitButton() added
[AT] - https://trello.com/c/EXaFtmtO/867-atmainguestbookv2form-testtextinmessagefieldwhenclicksubmitbutton-natalliaowl
> [AT][Main][guestbookv2][Form] testTextInMessageField_WhenClickSubmitButton() <NatalliaOwl>

- src/test/java/pages/base_abstract/FormPage.java
- src/test/java/tests/guest_book/SignGuestbookTest.java
testUrlPromptAlertsDisappear_WhenClickCancelButton() added,
dismissTwoAlerts() method created
[AT] - https://trello.com/c/7yv1jM60/868-atmainguestbookv2form-testurlpromptalertsdisappearwhenclickcancelbutton-natalliaowl
> [AT][Main][guestbookv2][Form] testUrlPromptAlertsDisappear_WhenClickCancelButton() <NatalliaOwl>
