RedRoverSchool/AutomationQA_05

src/test/java/LessonsTest.java

[US] - https://trello.com/c/r8lB6dzU/32-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/zq153dbp/61-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-lessons
[AT] - https://trello.com/c/AOxYQgaj/93-atsearchform-testsearchforlanguagebynamehappypath-lessons

[AT][Search][form] testSearchForLanguageByName_HappyPath() <Lessons>

---

src/test/java/JulieMykTest.java

[US] - https://trello.com/c/eVTF1feF/31-usfunctionalsearchform-search-for-language-field
[AT] - https://trello.com/c/ucKUevgO/100-atsearchform-testsearchforlanguagebynamehappypathjuliemyk
[TC] - https://trello.com/c/zbjlwIGy/66-tcsearchform-verify-if-searching-for-programming-language-by-name-he-can-see-the-list-of-related-results-juliemyk

[AT][Search][form] testSearchForLanguageByName_HappyPath() <JulieMyk>

---

src/test/java/RustamKhudoyarovTest.java

Added test testSearchLanguageField_HappyPath()
[US] - https://trello.com/c/eAkTmbtI/92-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/Lofw9Uao/89-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-rustamkhudoyar
[AT] - https://trello.com/c/uBZApyhV/116-atsearchform-testsearchlanguagefieldhappyrustamkhudoyarov

[AT][Search][form] SearchLanguageField_testSearchLanguageField_Happy_<RustamKhudoyarov>

---

src/test/java/Vira05Test.java

[US] -https://trello.com/c/MCELBniT/30-usfunctionalsearchform-searchforlanguagepage
[TC] - https://trello.com/c/vwWY2Me9/76-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-reelative-results-vira05
[AT] - https://trello.com/c/rwtmrAKr/115-atsearchform-testsearchforlanguagebynamehappypath-vira05

[AT][Search][form] testSearchForLanguageByName_HappyPath()< Vira05>

---

src/test/java/Lenochkanik80Test.java

[US] - https://trello.com/c/BKmPJfdX/35-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/rayFETA9/67-tcsearchform-verify-if-user-searching-for-programming-language-by-name-he-can-see-the-list-of-related-results-lenochkanik80
[AT] -  https://trello.com/c/oyZXD5kQ/101-atsearchform-testsearchforlanguagebynamehappypath-lenochkanik80

[AT][Search][form] testSearchForLanguageByName_HappyPath() <Lenochkanik80>

---

src/test/java/NatalyaYanochkovaTest.java

testSearchLanguageFieldByName_HappyPath() added
[US][](https://trello.com/c/MJVRAwtT/124-usfunctionalsearchform-search-for-language-field)
[TC][](https://trello.com/c/FhCO8sqe/125-tcsearchformnatalyayanochkova-verify-if-user-is-searching-for-a-programming-language-by-name-he-can-see-the-list-of-relative-res)
[AT][](https://trello.com/c/uBIJTTUR/123-atsearchformtestsearchlanguagefieldbynamehappypathnatalyayanochkova)

[AT][Search][form]testSearchLanguageFieldByName_HappyPath<NatalyaYanochkova>

---

src/test/java/YuliyaShershenTest.java

[US] - https://trello.com/c/i45JeFpf/37-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/ZN11ge2W/81-tcsearchform-verify-if-user-searching-for-programming-language-in-search-field-by-name-user-can-see-the-list-of-relative-results
[AT] - https://trello.com/c/Y0TdcqhC/97-atsearchform-testsearchforlanguagebynamehappypath-yuliya-shershen

[AT][Search][form] testSearchForLanguageByName_HappyPath() <Yuliya Shershen>

---

src/test/java/ElenaStratTest.java

[US] https://trello.com/c/nFQtJ2G5/14-usfunctionalsearchform-search-for-language-field
[TC] https://trello.com/c/xGHPyLSR/62-tcstartform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-elenastrat
[AT] https://trello.com/c/sNeSIta2/103-atsearchform-testsearchforlanguagebynamehappypath-elenastrat

[AT][Search][form] testSearchForLanguageByName_HappyPath() <ElenaStrat>

---

src/test/java/NataliiaOliverTest.java

[US] - https://trello.com/c/9AT5KvuL/22-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/BbGI3hD0/65-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-nataliiaoliver
[AT] - https://trello.com/c/pmCYqoD2/96-atsearchform-testsearchforlanguagebynamehappypath-nataliiaoliver

[AT][Search][form] testSearchForLanguageByName_HappyPath() <NataliiaOliver>

---

src/test/java/JulykanTest.java

testSearchForLanguageByName_HappyPath
[US]https://trello.com/c/Yp7L6BKo/52-usfunctionalsearchform-search-for-language-field
[TC]https://trello.com/c/naPjrOji/58-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-julykan
[AT]https://trello.com/c/5UoOOe6E/119-atsearchform-testsearchforlanguagebynamehappypath-julykan

[AT][Search][form] testSearchForLanguageByName_HappyPath <julykan>

---

src/test/java/mbatozTest.java

testSearchForLanguageByName_HappyPath added
[US] https://trello.com/c/C1ouR1kx/24-usfunctionalsearchform-search-for-language-fieldmbatoz
[TC] https://trello.com/c/jkG5JJCE/82-tcstartform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-mbatoz
[AT] https://trello.com/c/2mojVMvn/112-atsearchform-testsearchforlanguagebynamehappypath-mbatoz

[AT][Search][form] testSearchForLanguageByName_HappyPath <mbatoz>

---

src/test/java/AnzhelikaBaaTest.java

[US] - https://trello.com/c/JvhSZDhW/15-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/GgAGeJLH/73-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-related-results-anzhelikabaa
[AT] - https://trello.com/c/ncnSI75O/105-atsearchformtestsearchforlanguagebynamehappypath-anzhelikabaa

[AT][Search][form]testSearchForLanguageByName_HappyPath()<AnzhelikaBaa>

---

src/test/java/EnmedvTest.java

testSearchLanguageByName_HappyPath() added
[US] - https://trello.com/c/mlPkPJV3/40-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/DIZa4n9E/69-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-enmedv
[AT] - https://trello.com/c/8YP3L9AM/109-atsearchform-testsearchlanguagebynamehappypath-enmedv

[AT][Search][form] testSearchLanguageByName_HappyPath() <Enmedv>

---

src/test/java/Yuliya14Test.java

[US] - https://trello.com/c/r8lB6dzU/32-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/zq153dbp/61-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-lessons
[AT] - https://trello.com/c/AOxYQgaj/93-atsearchform-testsearchforlanguagebynamehappypath-lessons

[AT][Search][form] testSearchForLanguageByName_HappyPath() <Yuliya14>

---

src/test/java/YulyaNyuTest.java

[US] - https://trello.com/c/mnQHN8Ak/90-usfunctionsearchform-search-for-language-field
[TC] - https://trello.com/c/XAe3lfPj/91-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-yulyanyu
[AT] - https://trello.com/c/QixwtuGL/113-atsearchform-testsearchforlanguagebynamehappypath-yulyanyu

[AT][Search][form]testSearchForLanguageByName_HappyPath() <YulyaNyu>

---

src/test/java/VerafesTest.java

testSearchLanguageByName_HappyPath added
[US] - https://trello.com/c/GRtgfi9k/45-usfunctionalsearch-search-for-language-field 
[TC] - https://trello.com/c/7Op5mHP4/132-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-verafes
[AT] - https://trello.com/c/Ld6ePLq6/133-atsearchform-testsearchforlanguagebynamehappypath-verafes

[AT][Search][form] testSearchLanguageByName_HappyPath() <verafes>

---

src/test/java/SvetaKhudovaTest.java

testSearchLanguageByName_HappyPath added
[US] - https://trello.com/c/GRtgfi9k/45-usfunctionalsearch-search-for-language-field
[TC] - https://trello.com/c/aRjytWzM/77-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-svetakhudova
[AT] https://trello.com/c/pzc8J67U/106-atsearchform-testsearchlanguagebynamehappypath-svetakhudova

[AT][Search][form] testSearchLanguageByName_HappyPath() <SvetaKhudova>

---

src/test/java/Albina_starTest.java

[US] - https://trello.com/c/hPoy7MDv/21-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/eSYlTy4f/83-tcstartform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-albina-star
[AT] - https://trello.com/c/ZNenlYV3/111-atsearchform-testsearchforlanguagebynamehappypathalbina-star

[AT][Search][form] testSearchForLanguageByName_HappyPath()<Albina-star>

---

src/test/java/VictoriaLemaTest.java

[US] - https://trello.com/c/BF2kTwGt/163-usfunctionalsearchform-search-for-language-field-victorialema
[TC] - https://trello.com/c/g8PfQpCz/80-tcsearchform-verify-if-user-is-searching-for-a-programming-language-by-name-he-can-see-the-list-of-relative-resultsvictorialema
[AT] - https://trello.com/c/4wPyIuVv/99-atsearchform-testsearchforlanguagebynamehappypath-victorialema

[AT][Search][form] testSearchForLanguageByName_HappyPath() <VictoriaLema>

---

src/test/java/ElenaKudTest.java

[TC] - https://trello.com/c/nyVdMKTW/169-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-elenakud
[AT] - https://trello.com/c/axSPzJ5s/170-atsearchform-testsearchforlanguagebynamehappypath-elenakud

[AT][Search][form] testSearchForLanguageByName_HappyPath() <ElenaKud>

---

src/test/java/AndreiMironauTest.java

testSearchForLanguageFieldByName_HappyPath() added
[US] - https://trello.com/c/gk73LnbY/48-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/XeSkl5Aw/78-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-andreimironau
[AT] - https://trello.com/c/fZKNVCIY/184-atsearchform-testsearchforlanguagefieldbynamehappypath-andreimironau

[AT][Search][form] testSearchForLanguageFieldByName_HappyPath() <AndreiMironau>

---

src/test/java/EvgenyZagrebelnikovTest.java

[US] - https://trello.com/c/f81zF7hj/191-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/KZS7U47u/188-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-evgenyzagrebel
[AT] - https://trello.com/c/zWzhKZ7t/192-atsearchform-testsearchforlanguagebynamehappypath-evgenyzagrebelnikov

[AT][Search][form] testSearchForLanguageByName_HappyPath() <EvgenyZagrebelnikov>

---

src/test/java/Kot612005Test.java

testSearchForLanguageByName_HappyPath added
[US] - https://trello.com/c/KzRBItiq/168-usfunctionalsearchform-search-for-language-by-name
[TC] - https://trello.com/c/Qg73XGfR/180-tcsearchform-verify-if-user-is-searching-programming-language-by-name-he-can-see-the-list-of-relative-results-kot612005
[AT] - https://trello.com/c/iafiYr68/181-atsearchform-testsearchforlanguagebynamehappypathkot612005

[AT][Search][form]testSearchForLanguageByName_HappyPath<Kot612005>

---

src/test/java/IgorUlianovTest.java

[US] - https://trello.com/c/qZgsHeJm/197-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/mh31kza7/204-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-they-can-see-the-list-of-relative-results-igorulianov
[AT] - https://trello.com/c/kgixcFyY/208-atsearchform-testsearchforlanguagebynamehappypath-igorulianov

[AT][Search][form] testSearchForLanguageByName_HappyPath() <igorulianov>

---

src/test/java/MariaFrolovaTest.java

[US] - https://trello.com/c/TaJa6kot/196-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/pQDA2P97/205-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-can-see-the-list-of-relative-results-mariafrolova
[AT] - https://trello.com/c/hpb9kXat/209-atsearchform-testsearchforlanguagebynamehappypath-mariafrolova

[AT][Search][form] testSearchForLanguageByName_HappyPath() <MariaFrolova>

---

src/test/java/NataliaKengilTest.java

[US] - https://trello.com/c/ww9u8NiL/246-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/C5Xru0d2/247-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-nataliakengil
[AT] - https://trello.com/c/BmWIUnrf/248-atsearchform-testsearchforlanguagebynamehappypath-nataliakengil

[AT][Search][form] testSearchForLanguageByName_HappyPath() <NataliaKengil>

---

src/test/java/AramH20Test.java

[US] - https://trello.com/c/rwC2heKt/221-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/xU97Un5A/225-tcsearchform-verify-if-user-searching-for-programing-language-by-name-he-can-see-the-list-of-relative-results-aramh20
[AT] - https://trello.com/c/OIMp58dd/226-atsearchform-testsearchforlanguagebynamehappypath-aramh20

[AT][Search][form] testSearchForLanguageByName_HappyPath() <AramH20>

---

src/test/java/Katy1313Test.java

testSearchLanguageByName_HappyPath() added
[TC] - https://trello.com/c/cHa6Ao7R/160-tcsearchform-verify-that-the-user-is-able-to-search-for-a-programming-language-by-name-and-able-to-see-the-list-of-relative-resu
[AT] - https://trello.com/c/HKiFJpQV/162-atsearchform-testsearchlanguagebynamehappypath-katy1313

[AT][Search][form] testSearchLanguageByName_HappyPath() <katy1313>

---

src/test/java/AnaLaraTest.java

testSearchLanguageField_HappyPath added
[US] https://trello.com/c/Pfi21TZq/49-usfunctionalsearchform-search-for-language-feild
[TC] https://trello.com/c/NSs9ExK4/255-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-and-can-see-the-list-of-relative-results-analara
[AT] https://trello.com/c/z0h5ZbRP/257-atsearchform-testsearchforlanguagebynamehappypath-analara

[AT][Functional][Search][form] testSearchForLanguageByName_HappyPath() <AnaLara>

---

src/test/java/Kot612005Test.java

testClickOnStartInFooter_HappyPath added
[US] https://trello.com/c/2186kyHh/238-usmainfooterstart-after-clicking-on-start-field-base-url-stays-the-samekot612005
[TC] https://trello.com/c/fPwnCAwN/233-tcmainfooterstart-after-clicking-on-start-field-base-url-stays-the-samekot612005
[AT] https://trello.com/c/19bCqUd1/235-atmainfooterstart-after-clicking-on-start-field-base-url-stays-the-samekot612005

[AT][Main][footer][start]testClickOnStartInFooter_HappyPath<Kot612005>

---

src/test/java/NstzyaTest.java

testHistoricInfoLink_WhenClickingOnLink_HappyPath() changed location of final variables
[RF] - https://trello.com/c/Y430ucP7/277-rfstartmainlink-testhistoricinfolinkwhenclickingonlinkhappypath-nstzya

[RF][Start][main][link] testHistoricInfoLink_WhenClickingOnLink_HappyPath() <Nstzya>

---

src/test/java/VictoriaLemaTest.java

testIfToplistsFooterMenRedirectsToPageWithInformation_WhenClickingOnIt added
[US]-https://trello.com/c/AkkS2Fch/215-usmainfootertoplist-functionality-of-top-list-menu-on-footervictorialema
[TC]-https://trello.com/c/egR9vogF/234-tcmainfootertoplist-verify-if-user-can-see-the-table-of-top-rated-languages-with-information-using-the-footer-menu-victorialema
[AT]-https://trello.com/c/2ssDZ5TU/237-atmainfootertoplist-testiftoplistsfootermenredirectstopagewithinformationwhenclickingonit-victorialema

[AT][Main][footer][toplist] testIfToplistsFooterMenRedirectsToPageWithInformation_WhenClickingOnIt <VictoriaLema>

---

src/test/java/NatalliaOwlTest.java

[US] - https://trello.com/c/f81zF7hj/191-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/9bjeu7Oo/276-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-natalliaowl
[AT] - https://trello.com/c/XoEDeU6s/306-atsearchform-testsearchforlanguagebynamehappypath-natalliaowl

[AT][Search][form] testSearchForLanguageByName_HappyPath()<NatalliaOwl>

---

src/test/java/Katy1313Test.java

testBrowseLanguagesLanguagesSortedAscending_HappyPath() added
[TC] - https://trello.com/c/GmvSndKd/309-tcmainnavigationmenuabc-verify-that-when-a-user-clicks-on-any-letter-all-languages-starting-with-that-letter-are-shown-sorted-by
[AT] - https://trello.com/c/KAoFbdIi/310-atmainnavigationmenuabc-browselanguageslanguagessortedascending-katy1313

[AT][Main][navigation][menu][abc] testBrowseLanguagesLanguagesSortedAscending_HappyPath <katy1313>

---

src/test/java/Katy1313Test.java

testBrowseLanguagesLanguageSelectionH2HeaderTitle_HappyPath() added
[TC] - https://trello.com/c/Lto2dBSE/329-tcmainnavigationmenuabc-verify-that-when-a-user-selects-a-language-from-the-list-a-user-gets-redirected-to-a-new-page-with-katy1
[AT] - https://trello.com/c/EHLl0TjG/330-atmainnavigationmenuabc-browselanguageslanguageselectionh2headertitle-katy1313

[AT][Main][navigation][menu][abc] testBrowseLanguagesLanguageSelectionH2HeaderTitle_HappyPath() <katy1313>

---

src/test/java/MariaYanuTest.java

testHeaderOnTheStartPage() added
US:https://trello.com/c/09n8333z/287-usmainnavigationmenustart-after-clicking-on-start-in-the-navigation-menu-a-user-will-see-the-welcome-to-99-bottles-of-beer-heade
TC: https://trello.com/c/pNB1b5Z6/293-tcmainnavigationmenustart-on-the-start-page-user-should-be-able-to-read-the-welcome-to-99-bottles-of-beer-header-mariayanu
AT: https://trello.com/c/YgWU3FT5/352-atmainnavigationmenustart-on-the-start-page-user-should-be-able-to-read-the-welcome-to-99-bottles-of-beer-header-mariayanu

[AT][Main][navigation][menu][start] on the 'START' page user should be able to read the 'Welcome to 99 Bottles of Beer' header <MariaYanu>

---

src/test/java/IrinaDud_Test.java

[US]-https://trello.com/c/72sUwOoc/295-usfunctionalsearchform-search-for-language-field
[TC]-https://trello.com/c/0i03EqBJ/299-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-results-irinadud
[AT]-https://trello.com/c/6gg9Dh3V/301-atsearchform-testsearchforlanguagebynamehappypath-irinadud

[AT][Search][form] testSearchForLanguageByName_HappyPath() <IrinaDud>

---

src/test/java/ViktoryiaKudrautsavaTest.java

[US] - https://trello.com/c/aWrRBtWm/419-usfunctionalsearchform-search-for-language-field
[TC] - https://trello.com/c/9gF1mVlm/418-tcsearchform-verify-if-user-is-searching-for-programming-language-by-name-he-can-see-the-list-of-relative-resultsviktoryiakudrau
[AT] - https://trello.com/c/suzOKEA2/426-atsearchform-testsearchforlanguagebynamehappypath-viktoryiakudrautsava

[AT][Search][form] testSearchForLanguageByName_HappyPath() <ViktoryiaKudrautsava>

---

src/test/java/AnzhelikaBaaTest.java

testH2TagText_WhenSearchingLanguagesStartWithLetterA_HappyPath() added
[TC][A][main][header][h2] - https://trello.com/c/87ua0B0x/464-tcamainheaderh2-verify-text-of-the-header-on-page-where-all-languages-start-with-the-letter-a-anzhelikabaa
[AT][A][main][header][h2] - https://trello.com/c/UQLGWOgR/466-atamainheaderh2-pr-name-anzhelikabaa

[AT][A][main][header][h2]testH2TagText_WhenSearchingLanguagesStartWithLetterA_HappyPath() <AnzhelikaBaa>

---

src/test/java/VictoriaLemaTest.java

testErrorMessageTextAfterIncompleteInput() added, locators and a method created
[TC]-https://trello.com/c/KdJlJlfX/473-tcsubmitnewlanguagemaintext-verify-if-user-will-see-an-appropriate-error-message-if-he-doesnt-pass-security-check-victorialema
[AT]-https://trello.com/c/7HINAkBm/475-atsubmitnewlanguagemaintext-testerrormessagetextafterincompleteinput-victorialema

[AT][Submitnewlanguage][Main][text] testErrorMessageTextAfterIncompleteInput() <VictoriaLema>

---

src/test/java/NstzyaTest.java

testHeaderH2Text_WhenOpenBrowseLanguageMenu_PageBSubmenu_HappyPath() added
[US] - https://trello.com/c/pWfjZS54/520-usbmainheaderh2-verify-header-h2-in-tab-browse-language-of-menu-and-page-b-of-submenu
[TC] - https://trello.com/c/pTGxYUTC/521-tcbmainheaderh2-verify-header-h2-in-tab-browse-language-page-b-nstzya
[AT] - https://trello.com/c/sOCbXFG8/522-atbmainheaderh2-testheaderh2textwhenopenbrowselanguagemenupagebsubmenuhappypath-nstzya

[AT][B][main][header][h2] testHeaderH2Text_WhenOpenBrowseLanguageMenu_PageBSubmenu_HappyPath() <Nstzya>

---

src/test/java/NstzyaTest.java

testRandomLinkIsClickable_whenOpenBrowseLanguageMenu_JSubmenu_HappyPath() added
[US] - https://trello.com/c/MMiUJpb8/551-usjmaintablelink-verify-random-link-in-table-is-clickable-when-open-browse-language-in-menu-and-j-in-submenu
[TC] - https://trello.com/c/DmuXvssQ/552-tcjmaintablelink-verify-random-link-in-table-is-clickable-when-open-browse-language-in-menu-and-j-in-submenu-nstzya
[AT] - https://trello.com/c/pCGvFT41/553-atjmaintablelink-testrandomlinkisclickablewhenopenbrowselanguagemenujsubmenuhappypath-nstzya

[AT][J][main][table][link] testRandomLinkIsClickable_whenOpenBrowseLanguageMenu_JSubmenu_HappyPath <Nstzya>

---

src/test/java/MariaKuzhTest.java

testSortinglanguagesByNumber_AfterSelectingNumberInSubmenu() added
[US] - https://trello.com/c/dXYkpdHQ/524-usabcnavigationsubmenuzero-search-for-language-by-number
[TC] - https://trello.com/c/T2hdwlS9/560-tcabcnavigationsubmenuzero-verify-that-languages-are-sorted-and-displayed-on-the-page-abc-by-selected-number-of-submenu-mariakuz
[AT] - https://trello.com/c/fmVfQnxd/561-atabcnavigationsubmenuzero-testsortinglanguagesbynumberafterselectingnumberinsubmenumariakuzh

[AT][ABC][navigation][submenu][zero] testSortinglanguagesByNumber_AfterSelectingNumberInSubmenu()<MariaKuzh>

---

src/test/java/old_tests/NstzyaTest.java

testLinkText_WhenNavigatingFromStartToBrowseLanguageAndToLetterNLink_HappyPath() added
[US] - https://trello.com/c/qUba0ugY/611-usabcnavigationsubmenun-verify-text-in-the-link-when-open-browse-language-and-then-letter-n-links
[TC] - https://trello.com/c/PJCzOhZy/613-tcabcnavigationsubmenun-verify-text-in-the-header-h2-and-in-the-link-when-open-browse-language-and-then-letter-n-links-nstzya
[AT] - https://trello.com/c/lNTInU8A/614-atabcnavigationsubmenun-testlinktextwhennavigatingfromstarttobrowselanguageandtoletternlinkhappypath-nstzya

[AT][ABC][navigation][submenu][n] testLinkText_WhenNavigatingFromStartToBrowseLanguageAndToLetterNLink_HappyPath <Nstzya>

---

src/test/java/pages/BrowseLanguagesSubmenuPage.java
src/test/java/tests/KTest.java

testAllLanguagesNamesOnKPageStartWithLetterK() created,
Webelement and method added to BrowseLanguageSubmenuPage
[AT] - https://trello.com/c/d38s1NR4/666-atpomabcnavigationsubmenuk-testalllanguagesonkpagebeginwithletterk-natalliaowl

[AT][POM][ABC][navigation][submenu][k] testAllLanguagesOnKPageBeginWithLetterK <NatalliaOwl>

---

src/test/java/pages/start/HistoryPage.java
src/test/java/tests/HistoryTest.java

testHistorySubmenu tests refactored:
- testLabelTextSubmenuInfo() deleted
- testLinkTextSubmenuInfo() refactored
- testHistorySubmenu_NavigatesTo_HistorySubmenuPage() renamed and fixed
[RF] https://trello.com/c/QCVhOeVr/690-rfstartnavigationsubmenuinfo-testhistorysubmenu-refactored-verafes

[RF][Start][navigation][submenu][info] testHistorySubmenu refactored <verafes>

---

src/test/java/pages/base_abstract/TablePage.java
src/test/java/tests/JavaScriptLanguageTest.java

testJSDeepLinkText() added
(the deep link text is hyperlinked)
[AT] https://trello.com/c/O9ghltC5/736-atlanguagejavascript1948maintablelink-testjsdeeplinktext-verafes
[TC] https://trello.com/c/8xBbqp7N/737-tcpomlanguagejavascript1948maintablelink-verify-js-deep-link-href-text-verafes

[AT][LanguageJavascript1948][main][table][link] testJSDeepLinkText() <verafes>

---

src/test/java/tests/YTest.java

The testRandomLinkNavigatesToCorrespondingPage() was ignored, the screenshot is attached in the RF card
[RF] - https://trello.com/c/SHz5J9Wl/742-rferrorignoretestrandomlinknavigatestocorrespondingpage-nataliiaoliver

[RF][Error][Ignore]testRandomLinkNavigatesToCorrespondingPage() <NataliiaOliver>

---

src/test/java/pages/base_abstract/TablePage.java
src/test/java/pages/browse_languages/languages/JavaScriptLanguagePage.java
src/test/java/tests/JavaScriptLanguageTest.java

testJavaScriptDeeLink_NavigatesTo_CorrespondingPage() added, 
TablePage: xpath fixed
[TC] - https://trello.com/c/AconBuLV/750-tcpomlanguagejavascript1948maintablelink-js-deep-link-navigates-to-external-page-verafes
[AT] - https://trello.com/c/bZ7iMhRh/751-atlanguagejavascript1948maintablelink-testjavascriptdeelinknavigatestocorrespondingexternalpage-verafes

[AT][LanguageJavascript1948][main][table][link] testJavaScriptDeeLink_NavigatesTo_CorrespondingPage() <verafes>

---

src/test/java/tests/api/API_JTest.java

Test_API_AllJLinksAreNotBroken() and test_API_AllImagesAreNotBroken() on J page are added
[AT] -https://trello.com/c/s0gwakoP/793-atapiabcnavigationsubmenuj-testapihttpresponselinksverafes

[AT][API][ABC][navigation][submenu][J] test_API_AllJLinksAndImagesAreNotBroken <verafes> 

---

src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
src/test/java/tests/submit_new_language/SubmitNewLanguageTest.java

Creted testNumberRequiredFieldWithRedBorder(), added locators and methods
[TC] - https://trello.com/c/cGl8luNA/822-tcsubmitnewlanguagemainform-verify-that-the-number-of-required-fields-when-clicking-the-button-submit-language-is-5-nataliiaoliv
[AT] - https://trello.com/c/5ZFAkEfk/823-atsubmitnewlanguagemainform-testnumberrequiredfieldwithredborder-nataliiaoliver

[AT][Submitnewlanguage][main][form] testNumberRequiredFieldWithRedBorder() <NataliiaOliver>
